import { env } from '@/lib/env';
import { supabase } from '@/lib/supabase';
import type { CloudinaryUploadResult } from '@/services/cloudinary.service';
const MAX=2*1024*1024;const ALLOWED:any={'jpg':'image/jpeg','jpeg':'image/jpeg','png':'image/png','pdf':'application/pdf'};
export function validateChatFile(file:File){if(!file)throw new Error('File wajib dipilih.');if(file.size>MAX)throw new Error('File chat maksimal 2MB.');const ext=file.name.split('.').pop()?.toLowerCase()||'';if(!ALLOWED[ext]||ALLOWED[ext]!==file.type)throw new Error('Format chat hanya JPG, PNG, atau PDF.');}
async function compressImage(file:File){if(file.type==='application/pdf')return file;const bitmap=await createImageBitmap(file);const scale=Math.min(1,512/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Browser tidak mendukung pemrosesan gambar.');ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);const blob=await new Promise<Blob|null>(r=>canvas.toBlob(r,'image/jpeg',0.84));bitmap.close();if(!blob)throw new Error('Gambar gagal diproses.');return new File([blob],`${file.name.replace(/\.[^.]+$/,'')}.jpg`,{type:'image/jpeg',lastModified:Date.now()});}
export async function uploadChatAttachment(file:File,threadId:string,ownerId:string,messageId?:string):Promise<CloudinaryUploadResult & {media_id:string;mime_type:string;size_bytes:number;expires_at:string}>{validateChatFile(file);const prepared=await compressImage(file);if(prepared.size>MAX)throw new Error('Ukuran hasil gambar masih di atas 2MB. Pilih gambar yang lebih kecil.');const pdf=prepared.type==='application/pdf';const form=new FormData();form.append('file',prepared);form.append('upload_preset',env.cloudinaryUploadPreset);form.append('folder',`sykabelajar/chat/${threadId}`);const response=await fetch(`https://api.cloudinary.com/v1_1/${env.cloudinaryCloudName}/${pdf?'raw':'image'}/upload`,{method:'POST',body:form});if(!response.ok)throw new Error(`Upload chat gagal (${response.status}).`);const result=await response.json() as CloudinaryUploadResult;const expiresAt=new Date(Date.now()+7*24*60*60*1000).toISOString();const{data,error}=await supabase.from('chat_media').insert({thread_id:threadId,message_id:messageId??null,owner_id:ownerId,public_id:result.public_id,secure_url:result.secure_url,resource_type:result.resource_type??(pdf?'raw':'image'),mime_type:prepared.type,size_bytes:prepared.size,expires_at:expiresAt}).select('id').single();if(error)throw error;return{...result,media_id:String(data.id),mime_type:prepared.type,size_bytes:prepared.size,expires_at:expiresAt};}
export async function attachChatMedia(mediaId:string,messageId:string){const{error}=await supabase.rpc('attach_chat_media',{p_media_id:mediaId,p_message_id:messageId});if(error)throw error;}
export function isImageUrl(text:string){const clean=text.trim().split(/[?#]/)[0].toLowerCase();return /\.(gif|jpe?g|png|webp|avif)$/i.test(clean);}
export function isGifUrl(text:string){const clean=text.trim().split(/[?#]/)[0].toLowerCase();return clean.endsWith('.gif');}
export function isHttpUrl(text:string){try{const u=new URL(text.trim());return u.protocol==='http:'||u.protocol==='https:';}catch{return false;}}
export function imageStyle(_url:string){return{maxWidth:'512px',maxHeight:'512px',width:'auto',height:'auto'} as const;}
