import { supabase } from '@/lib/supabase';
import { emitSykaEvent } from '@/lib/realtimeBus';
export type ChatThreadType='dm'|'ticket'|string;
export type FollowStatus='none'|'pending'|'approved'|'auto';
export interface ChatThread{id:string;user_id:string;participant_id?:string|null;status:'open'|'closed';rating:number|null;closed_at:string|null;created_at:string;thread_type?:ChatThreadType;subject?:string|null;description?:string|null;handled_by?:string|null;handled_at?:string|null;user_name?:string;username?:string;avatar_url?:string;other_user_name?:string;other_username?:string;other_avatar_url?:string;last_message?:string;last_message_at?:string;unread_count?:number}
export interface ChatMessage{id:string;thread_id:string;sender_id:string;body:string;created_at:string}
export interface ChatHistoryRow{thread_id:string;user_id:string;user_name:string;username:string|null;status:string;rating:number|null;handled_by:string|null;handled_name:string|null;handled_username:string|null;created_at:string;closed_at:string|null;subject:string|null;description:string|null;message_count:number}
export interface SearchUserResult{id:string;username:string;full_name:string;avatar_url:string|null}
function err(error:any){const m=String(error?.message??error??'Terjadi kesalahan.');const map:Record<string,string>={ACTIVE_TICKET_EXISTS:'Anda masih memiliki laporan yang sedang berjalan. Tunggu hingga laporan diselesaikan oleh Admin.',FOLLOW_REQUIRED:'Anda harus mengikuti pengguna tersebut dan menunggu persetujuan sebelum dapat mengirim pesan.',THREAD_CLOSED:'Percakapan ini sudah ditutup.',ACCESS_DENIED:'Anda tidak memiliki akses ke percakapan ini.',MESSAGE_REQUIRED:'Pesan tidak boleh kosong.',CHAT_BLOCKED:'Anda tidak dapat mengirim pesan karena hubungan chat diblokir.',TICKET_NOT_OPEN:'Ticket sudah tidak aktif.',TICKET_ALREADY_CLAIMED:'Ticket sudah diambil oleh petugas lain.',INVALID_RATING:'Rating harus 1-5.'};const k=Object.keys(map).find(x=>m.includes(x));return new Error(k?map[k]:m)}
let threadsCache: ChatThread[] | null = null;
let threadsCacheAt = 0;
let threadsInFlight: Promise<ChatThread[]> | null = null;
const THREADS_CACHE_MS = 20_000;
const THREADS_SERVER_LIMIT = 50;
let unreadCountCache: number | null = null;
let unreadCountCacheAt = 0;
let unreadCountInFlight: Promise<number> | null = null;
const UNREAD_COUNT_CACHE_MS = 15_000;
function invalidateChatCaches(){threadsCache=null;threadsCacheAt=0;unreadCountCache=null;unreadCountCacheAt=0}
export async function getOrCreateDmThread(otherUserId:string){const{data,error}=await supabase.rpc('get_or_create_dm_thread',{p_other_user_id:otherUserId});if(error)throw err(error);invalidateChatCaches();return data as ChatThread}
export async function loadMyThreads(force=false){const now=Date.now();if(!force&&threadsCache&&now-threadsCacheAt<THREADS_CACHE_MS)return threadsCache;if(!force&&threadsInFlight)return threadsInFlight;const request:Promise<ChatThread[]>=(async()=>{const{data,error}=await supabase.rpc('load_my_threads_v2',{p_limit:THREADS_SERVER_LIMIT});if(error)throw error;const rows=(data??[])as ChatThread[];threadsCache=rows;threadsCacheAt=Date.now();return rows})();threadsInFlight=request;try{return await request}finally{if(threadsInFlight===request)threadsInFlight=null}}
export async function sendMessage(threadId:string,body:string){const text=body.trim();if(!text)throw new Error('MESSAGE_REQUIRED');const{data,error}=await supabase.rpc('send_chat_message',{p_thread_id:threadId,p_body:text});if(error)throw err(error);invalidateChatCaches();emitSykaEvent({type:'chat-unread',threadId});return data as ChatMessage}
export async function loadChatMessagesPage(threadId:string,limit=50,before?:string|null){const{data,error}=await supabase.rpc('get_chat_messages_page',{p_thread_id:threadId,p_limit:Math.min(Math.max(limit,1),100),p_before:before??null});if(error)throw err(error);return[...(data??[])].reverse()as ChatMessage[]}
export async function markThreadRead(threadId:string){const{error}=await supabase.rpc('mark_chat_thread_read',{p_thread_id:threadId});if(error)throw err(error);invalidateChatCaches();emitSykaEvent({type:'chat-read',threadId})}
export async function getUnreadChatCount(force=false){const now=Date.now();if(!force&&unreadCountCache!==null&&now-unreadCountCacheAt<UNREAD_COUNT_CACHE_MS)return unreadCountCache;if(!force&&unreadCountInFlight)return unreadCountInFlight;const request:Promise<number>=(async()=>{const{data,error}=await supabase.rpc('get_my_unread_chat_count');if(error)throw error;const value=Number(data??0);unreadCountCache=value;unreadCountCacheAt=Date.now();return value})();unreadCountInFlight=request;try{return await request}finally{if(unreadCountInFlight===request)unreadCountInFlight=null}}
export async function closeThread(threadId:string,rating?:number){if(rating!==undefined&&(!Number.isInteger(rating)||rating<1||rating>5))throw new Error('INVALID_RATING');const{data,error}=await supabase.rpc('close_chat_thread',{p_thread_id:threadId,p_rating:rating??null});if(error)throw err(error);invalidateChatCaches();return data as ChatThread}
export async function claimChatTicket(threadId:string){const{data,error}=await supabase.rpc('claim_chat_ticket',{p_thread_id:threadId});if(error)throw err(error);invalidateChatCaches();return data as ChatThread}
export async function getAdminChatHistory(opts:{search?:string;rating?:number|null;handledBy?:string|null;sortDesc?:boolean;limit?:number}={}){const{data,error}=await supabase.rpc('get_admin_chat_history',{p_search:opts.search??null,p_rating:opts.rating??null,p_handled_by:opts.handledBy??null,p_sort_desc:opts.sortDesc!==false,p_limit:opts.limit??100});if(error)throw err(error);return(data??[])as ChatHistoryRow[]}
export async function submitRating(threadId:string,rating:number){return closeThread(threadId,rating)}
export async function createTicketThread(subject:string,description:string){const s=subject.trim(),d=description.trim();if(!s)throw new Error('Subjek wajib diisi.');if(!d)throw new Error('Deskripsi wajib diisi.');const{data,error}=await supabase.rpc('create_ticket_thread',{p_subject:s,p_description:d});if(error)throw err(error);invalidateChatCaches();return data as ChatThread}
export const loadMyThread=async()=>{const t=await loadMyThreads();return t.find(x=>x.thread_type==='ticket'&&x.status==='open')??null};
export async function searchUsersForChat(query:string,limit=10){const q=query.trim();if(!q)return[];const{data:auth}=await supabase.auth.getSession();if(!auth.session?.user)return[];const safe=q.replace(/[%_,]/g,' ');const{data,error}=await supabase.from('profiles').select('id,username,full_name,avatar_url').or(`full_name.ilike.%${safe}%,username.ilike.%${safe}%`).neq('id',auth.session.user.id).limit(limit);if(error)throw error;return(data??[]).map((r:any)=>({id:r.id,username:r.username??'',full_name:r.full_name??'',avatar_url:r.avatar_url??null}))}
export const createDmFromProfile=getOrCreateDmThread;
export async function getFollowStatus(followerId:string,followingId:string){const{data,error}=await supabase.rpc('get_follow_status',{p_follower_id:followerId,p_following_id:followingId});if(error)throw error;return((data as FollowStatus)||'none')}
export async function requestFollow(targetUserId:string){const{data,error}=await supabase.rpc('create_follow_request',{p_target_user_id:targetUserId});if(error)throw err(error);emitSykaEvent({type:'follow-updated',userId:targetUserId,status:String((data as any)?.status??'pending')});return data as any}
export async function respondFollowRequest(followerId:string,accept:boolean){const{data,error}=await supabase.rpc('respond_follow_request',{p_follower_id:followerId,p_accept:accept});if(error)throw err(error);emitSykaEvent({type:'follow-updated',userId:followerId,status:accept?'approved':'none'});return data}
export async function removeFollow(targetUserId:string){const{error}=await supabase.rpc('remove_follow',{p_target_user_id:targetUserId});if(error)throw err(error);emitSykaEvent({type:'follow-updated',userId:targetUserId,status:'none'})}
export async function isFollowApproved(followerId:string,followingId:string){const s=await getFollowStatus(followerId,followingId);return s==='approved'||s==='auto'}
export async function getUserPrivacy(userId:string){const{data,error}=await supabase.from('profiles').select('accept_messages').eq('id',userId).maybeSingle();if(error)throw error;return data?.accept_messages??'public'}
export async function blockChatUser(targetUserId:string){const{error}=await supabase.rpc('block_chat_user',{p_target_user_id:targetUserId});if(error)throw err(error);invalidateChatCaches();emitSykaEvent({type:'chat-blocked',userId:targetUserId})}
export async function unblockChatUser(targetUserId:string){const{error}=await supabase.rpc('unblock_chat_user',{p_target_user_id:targetUserId});if(error)throw err(error);invalidateChatCaches();emitSykaEvent({type:'chat-unblocked',userId:targetUserId})}
export async function isChatBlocked(targetUserId:string){const{data:auth}=await supabase.auth.getSession();if(!auth.session?.user)return false;const{data,error}=await supabase.rpc('is_chat_blocked',{p_a:auth.session.user.id,p_b:targetUserId});if(error)throw err(error);return Boolean(data)}
export async function hideChatThread(threadId:string){const{error}=await supabase.rpc('hide_chat_thread',{p_thread_id:threadId});if(error)throw err(error);invalidateChatCaches();emitSykaEvent({type:'chat-hidden',threadId})}
export async function canDmUser(currentUserId:string,targetUserId:string){return (await isFollowApproved(currentUserId,targetUserId))&&!(await isChatBlocked(targetUserId))}
export async function acceptFollow(followerId:string,_followingId:string){return respondFollowRequest(followerId,true)}
export async function rejectFollow(followerId:string,_followingId:string){return respondFollowRequest(followerId,false)}
