import { supabase } from '@/lib/supabase';

export interface CommerceProduct {
  id: string; code: string; slug: string; name: string; short_description: string | null; product_type: string; audiences: string[] | null; price: number; currency: string; image_url: string | null; public_id: string | null; is_active: boolean; is_featured: boolean; sort_order: number;
}
export interface OrganizerPlanCatalogRow { plan_code: string; name: string; badge: string | null; description: string | null; monthly_price: number; yearly_price: number; monthly_discount_percent: number; yearly_discount_percent: number; currency: string; sort_order: number; is_active: boolean; }
export interface OrganizerPlanBenefit { plan_code: string; capability: string; limit_value: number | null; config: Record<string, unknown>; }
export interface OrganizerVoucher { id: string; code: string; title: string | null; description: string | null; benefit_type: 'DISCOUNT_PERCENT' | 'FREE_PLAN'; discount_percent: number; free_plan_code: string | null; free_duration_days: number | null; target_plan_codes: string[]; target_billing_periods: string[]; max_uses: number; claim_count: number; used_count: number; is_active: boolean; starts_at: string | null; ends_at: string | null; claimed: boolean; created_by: string | null; created_at: string; used_at: string | null; }
export interface OrganizerVoucherClaim { id: string; voucher_id: string; organizer_id: string; claimed_by: string; claimed_at: string; used_at: string | null; used_order_id: string | null; status: 'CLAIMED' | 'USED' | 'CANCELLED'; }
export interface OrganizerPaymentConfig { mode: 'MANUAL_TRANSFER' | 'MIDTRANS'; manual: { bank_name: string; account_number: string; account_name: string; instructions: string; }; midtrans: { environment: 'sandbox' | 'production'; client_key: string; }; }
export interface OrganizerPaymentFieldSetting { id: string; field_key: string; label: string; description: string; is_enabled: boolean; is_required: boolean; sort_order: number; input_type: 'TEXT' | 'NUMBER'; }
export interface OrganizerPaymentMethod { id: string; name: string; payment_type: string; details: Record<string, unknown>; is_active: boolean; sort_order: number; created_at: string; updated_at: string; }

function mapVoucher(row: Record<string, unknown>): OrganizerVoucher { return { id: String(row.id), code: String(row.code), title: row.title == null ? null : String(row.title), description: row.description == null ? null : String(row.description), benefit_type: String(row.benefit_type ?? 'DISCOUNT_PERCENT') as OrganizerVoucher['benefit_type'], discount_percent: Number(row.discount_percent ?? 0), free_plan_code: row.free_plan_code == null ? null : String(row.free_plan_code), free_duration_days: row.free_duration_days == null ? null : Number(row.free_duration_days), target_plan_codes: Array.isArray(row.target_plan_codes) ? row.target_plan_codes.map(String) : [], target_billing_periods: Array.isArray(row.target_billing_periods) ? row.target_billing_periods.map(String) : ['MONTHLY', 'YEARLY'], max_uses: Number(row.max_uses ?? 1), claim_count: Number(row.claim_count ?? 0), used_count: Number(row.used_count ?? 0), is_active: Boolean(row.is_active), starts_at: row.starts_at == null ? null : String(row.starts_at), ends_at: row.ends_at == null ? null : String(row.ends_at), claimed: Boolean(row.claimed), created_by: row.created_by == null ? null : String(row.created_by), created_at: String(row.created_at ?? ''), used_at: row.used_at == null ? null : String(row.used_at) }; }
function mapPaymentField(row: Record<string, unknown>): OrganizerPaymentFieldSetting { return { id: String(row.id), field_key: String(row.field_key), label: String(row.label), description: String(row.description ?? ''), is_enabled: Boolean(row.is_enabled), is_required: Boolean(row.is_required), sort_order: Number(row.sort_order ?? 0), input_type: String(row.input_type ?? 'TEXT').toUpperCase() === 'NUMBER' ? 'NUMBER' : 'TEXT' }; }
function mapPaymentMethod(row: Record<string, unknown>): OrganizerPaymentMethod { return { id: String(row.id), name: String(row.name ?? ''), payment_type: String(row.payment_type ?? ''), details: row.details && typeof row.details === 'object' ? row.details as Record<string, unknown> : {}, is_active: Boolean(row.is_active), sort_order: Number(row.sort_order ?? 0), created_at: String(row.created_at ?? ''), updated_at: String(row.updated_at ?? '') }; }

export async function listActiveProducts(): Promise<CommerceProduct[]> { const { data, error } = await supabase.from('commerce_products').select('id,code,slug,name,short_description,product_type,audiences,price,currency,image_url,public_id,is_active,is_featured,sort_order').eq('is_active', true).order('sort_order', { ascending: true }); if (error) throw error; return ((data ?? []) as Array<Record<string, unknown>>).map((p) => ({ id: String(p.id), code: String(p.code ?? ''), slug: String(p.slug ?? ''), name: String(p.name ?? ''), short_description: p.short_description == null ? null : String(p.short_description), product_type: String(p.product_type ?? ''), audiences: Array.isArray(p.audiences) ? p.audiences.map(String) : null, price: Number(p.price ?? 0), currency: String(p.currency ?? 'IDR'), image_url: p.image_url == null ? null : String(p.image_url), public_id: p.public_id == null ? null : String(p.public_id), is_active: Boolean(p.is_active), is_featured: Boolean(p.is_featured), sort_order: Number(p.sort_order ?? 0) })); }
export async function listActiveOrganizerPlans(): Promise<OrganizerPlanCatalogRow[]> { const { data, error } = await supabase.from('plan_catalog').select('plan_code,name,badge,description,monthly_price,yearly_price,monthly_discount_percent,yearly_discount_percent,currency,sort_order,is_active').eq('is_active', true).in('plan_code', ['FREE','PREMIUM','PRO']).order('sort_order', { ascending: true }); if (error) throw error; return ((data ?? []) as Array<Record<string, unknown>>).map((p) => ({ plan_code: String(p.plan_code), name: String(p.name ?? p.plan_code), badge: p.badge == null ? null : String(p.badge), description: p.description == null ? null : String(p.description), monthly_price: Number(p.monthly_price ?? 0), yearly_price: Number(p.yearly_price ?? 0), monthly_discount_percent: Number(p.monthly_discount_percent ?? 0), yearly_discount_percent: Number(p.yearly_discount_percent ?? 0), currency: String(p.currency ?? 'IDR'), sort_order: Number(p.sort_order ?? 0), is_active: Boolean(p.is_active) })); }
export async function listOrganizerPlanBenefits(planCodes: string[]): Promise<OrganizerPlanBenefit[]> { const normalized = [...new Set(planCodes.map((code) => code.trim().toUpperCase()).filter(Boolean))]; if (!normalized.length) return []; const { data, error } = await supabase.from('plan_entitlements').select('plan_code,capability,limit_value,config').in('plan_code', normalized).order('plan_code').order('capability'); if (error) throw error; return ((data ?? []) as Array<Record<string, unknown>>).map((row) => ({ plan_code: String(row.plan_code), capability: String(row.capability), limit_value: row.limit_value == null ? null : Number(row.limit_value), config: row.config && typeof row.config === 'object' ? row.config as Record<string, unknown> : {} })); }
export async function listClaimableOrganizerVouchers(): Promise<OrganizerVoucher[]> { const { data, error } = await supabase.rpc('list_claimable_organizer_vouchers'); if (error) throw error; return ((data ?? []) as Array<Record<string, unknown>>).map(mapVoucher); }
export async function claimOrganizerVoucher(voucherId: string): Promise<OrganizerVoucherClaim> { const { data, error } = await supabase.rpc('claim_organizer_voucher', { p_voucher_id: voucherId }); if (error) throw error; const row = Array.isArray(data) ? data[0] : data; if (!row) throw new Error('Voucher gagal di-claim.'); return { id: String(row.id), voucher_id: String(row.voucher_id), organizer_id: String(row.organizer_id), claimed_by: String(row.claimed_by), claimed_at: String(row.claimed_at), used_at: row.used_at == null ? null : String(row.used_at), used_order_id: row.used_order_id == null ? null : String(row.used_order_id), status: String(row.status) as OrganizerVoucherClaim['status'] }; }
export async function validateOrganizerVoucher(code: string, planCode?: string, billingPeriod?: 'MONTHLY' | 'YEARLY') { const { data, error } = await supabase.rpc('validate_organizer_voucher', { p_code: code.trim().toUpperCase(), p_plan_code: planCode?.trim().toUpperCase() || null, p_billing_period: billingPeriod ?? null }); if (error) throw error; const row = Array.isArray(data) ? data[0] : data; return { isValid: Boolean(row?.is_valid), discountPercent: Number(row?.discount_percent ?? 0), benefitType: String(row?.benefit_type ?? ''), freePlanCode: row?.free_plan_code == null ? null : String(row.free_plan_code), freeDurationDays: row?.free_duration_days == null ? null : Number(row.free_duration_days), voucherId: row?.voucher_id == null ? null : String(row.voucher_id), message: String(row?.message ?? '') }; }
export async function listOrganizerVouchers(): Promise<OrganizerVoucher[]> { const { data, error } = await supabase.from('organizer_vouchers').select('id,code,title,description,benefit_type,discount_percent,free_plan_code,free_duration_days,target_plan_codes,target_billing_periods,max_uses,claim_count,used_count,is_active,starts_at,ends_at,created_by,created_at,used_at').order('created_at',{ascending:false}).limit(100); if (error) throw error; return ((data ?? []) as Array<Record<string, unknown>>).map(mapVoucher); }
export async function adminUpsertOrganizerVoucher(input: { id?: string | null; title: string; description?: string; benefitType: 'DISCOUNT_PERCENT' | 'FREE_PLAN'; discountPercent?: number; freePlanCode?: string; freeDurationDays?: number; targetPlanCodes: string[]; targetBillingPeriods: string[]; maxUses: number; startsAt?: string | null; endsAt?: string | null; isActive: boolean; }) { const { data, error } = await supabase.rpc('admin_upsert_organizer_voucher', { p_id: input.id ?? null, p_title: input.title.trim() || null, p_description: input.description?.trim() || null, p_benefit_type: input.benefitType, p_discount_percent: Number(input.discountPercent ?? 0), p_free_plan_code: input.freePlanCode?.trim().toUpperCase() || null, p_free_duration_days: input.freeDurationDays ?? null, p_target_plan_codes: input.targetPlanCodes, p_target_billing_periods: input.targetBillingPeriods, p_max_uses: input.maxUses, p_starts_at: input.startsAt ?? null, p_ends_at: input.endsAt ?? null, p_is_active: input.isActive }); if (error) throw error; const row = Array.isArray(data) ? data[0] : data; return row ? mapVoucher(row as Record<string, unknown>) : null; }
export async function listOrganizerPaymentFieldSettings(): Promise<OrganizerPaymentFieldSetting[]> { const { data, error } = await supabase.rpc('list_organizer_payment_field_settings'); if (error) throw error; return ((data ?? []) as Array<Record<string, unknown>>).map(mapPaymentField); }
export async function adminSaveOrganizerPaymentFields(fields: Array<Omit<OrganizerPaymentFieldSetting, 'id'>>): Promise<OrganizerPaymentFieldSetting[]> { const { data, error } = await supabase.rpc('admin_save_organizer_payment_fields', { p_fields: fields }); if (error) throw error; return ((data ?? []) as Array<Record<string, unknown>>).map(mapPaymentField); }
export async function listOrganizerPaymentMethods(): Promise<OrganizerPaymentMethod[]> { const { data, error } = await supabase.rpc('list_organizer_payment_methods'); if (error) throw error; return ((data ?? []) as Array<Record<string, unknown>>).map(mapPaymentMethod); }
export async function adminCreateOrganizerPaymentMethod(input: { name: string; paymentType: string; details: Record<string, unknown>; sortOrder?: number }): Promise<OrganizerPaymentMethod> { const { data, error } = await supabase.rpc('admin_create_organizer_payment_method', { p_name: input.name.trim(), p_payment_type: input.paymentType.trim().toUpperCase(), p_details: input.details, p_sort_order: Number(input.sortOrder ?? 0) }); if (error) throw error; const row = Array.isArray(data) ? data[0] : data; if (!row) throw new Error('Metode pembayaran gagal dibuat.'); return mapPaymentMethod(row as Record<string, unknown>); }
export async function adminDeleteOrganizerPaymentMethod(id: string) { const { data, error } = await supabase.rpc('admin_delete_organizer_payment_method', { p_id: id }); if (error) throw error; return Boolean(data); }
export async function getOrganizerPaymentConfig(): Promise<OrganizerPaymentConfig> { const { data, error } = await supabase.rpc('get_organizer_payment_config'); if (error) throw error; const value = (Array.isArray(data) ? data[0] : data) as Record<string, any> | null; return { mode: value?.mode === 'MIDTRANS' ? 'MIDTRANS' : 'MANUAL_TRANSFER', manual: { bank_name: String(value?.manual?.bank_name ?? ''), account_number: String(value?.manual?.account_number ?? ''), account_name: String(value?.manual?.account_name ?? ''), instructions: String(value?.manual?.instructions ?? '') }, midtrans: { environment: value?.midtrans?.environment === 'production' ? 'production' : 'sandbox', client_key: String(value?.midtrans?.client_key ?? '') } }; }
export async function adminSaveOrganizerPaymentConfig(config: OrganizerPaymentConfig) { const { data, error } = await supabase.rpc('admin_save_organizer_payment_config', { p_config: config }); if (error) throw error; return data as OrganizerPaymentConfig; }
export async function listMyOrganizerPlanOrders() { const { data: sessionData } = await supabase.auth.getSession(); const userId = sessionData.session?.user?.id; if (!userId) return []; const { data, error } = await supabase.from('orders').select('id,status,subtotal,discount,total,currency,payment_method,payment_provider,payment_proof_url,payment_proof_public_id,payment_proof_width,payment_proof_height,payment_proof_version,payment_proof_status,contact_name,contact_email,contact_note,contact_fields,payment_method_id,admin_review_note,reviewed_at,created_at,order_items(id,name,product_type,product_ref,unit_price,line_total,metadata)').eq('user_id', userId).order('created_at',{ascending:false}).limit(20); if (error) throw error; return data ?? []; }
export async function createOrganizerPlanOrderV3(input: { organizerId: string; planCode: string; billingPeriod: 'MONTHLY' | 'YEARLY'; contactName?: string; contactEmail?: string; whatsapp?: string; contactNote?: string; contactFields?: Record<string, string>; paymentMethodId?: string; proofUrl?: string; proofPublicId?: string; proofWidth?: number; proofHeight?: number; proofVersion?: string; proofResourceType?: string; voucherCode?: string; }) { if (!input.organizerId) throw new Error('Organisasi wajib dipilih.'); if (!['PREMIUM','PRO'].includes(input.planCode.toUpperCase())) throw new Error('Plan berbayar tidak valid.'); const { data, error } = await supabase.rpc('create_organizer_plan_order_v3', { p_organizer_id: input.organizerId, p_plan_code: input.planCode.toUpperCase(), p_billing_period: input.billingPeriod, p_contact_name: input.contactName?.trim() || null, p_contact_email: input.contactEmail?.trim() || null, p_whatsapp: input.whatsapp?.trim() || null, p_contact_note: input.contactNote?.trim() || null, p_contact_fields: input.contactFields ?? {}, p_payment_method_id: input.paymentMethodId ?? null, p_proof_url: input.proofUrl?.trim() || null, p_proof_public_id: input.proofPublicId ?? null, p_proof_width: input.proofWidth ?? null, p_proof_height: input.proofHeight ?? null, p_proof_version: input.proofVersion ?? null, p_proof_resource_type: input.proofResourceType ?? null, p_voucher_code: input.voucherCode?.trim().toUpperCase() || null }); if (error) throw error; return Array.isArray(data) ? data[0] : data; }
export async function createOrganizerPlanOrderV2(input: { organizerId: string; planCode: string; billingPeriod: 'MONTHLY' | 'YEARLY'; whatsapp: string; proofUrl?: string; proofPublicId?: string; proofWidth?: number; proofHeight?: number; proofVersion?: string; proofResourceType?: string; voucherCode?: string; }) { return createOrganizerPlanOrderV3({ ...input, whatsapp: input.whatsapp }); }
export async function requestCustomOrganizerPlan(input: { organizerId: string; requestedFeatures: string[]; quantities?: Record<string, number>; notes?: string; contactWhatsapp?: string; }) { const features = input.requestedFeatures.map((x) => x.trim()).filter(Boolean); if (!input.organizerId) throw new Error('Organisasi wajib dipilih.'); if (!features.length) throw new Error('Pilih minimal satu fitur custom.'); const quantities: Record<string, number> = {}; for (const [key,value] of Object.entries(input.quantities ?? {})) { if (!features.includes(key)) continue; if (!Number.isInteger(value) || value < 1) throw new Error(`Jumlah untuk ${key} harus bilangan bulat minimal 1.`); quantities[key]=value; } const { data,error }=await supabase.rpc('request_custom_organizer_plan',{p_organizer_id:input.organizerId,p_requested_features:{features,quantities},p_notes:input.notes?.trim()||null,p_contact_whatsapp:input.contactWhatsapp?.trim()||null}); if(error)throw error; return Array.isArray(data)?data[0]:data; }
export async function createProductOrder(productId:string,quantity:number){if(!Number.isInteger(quantity)||quantity<1)throw new Error('Jumlah produk tidak valid.');const{data,error}=await supabase.rpc('create_product_order',{p_product_id:productId,p_quantity:quantity});if(error)throw error;return Array.isArray(data)?data[0]:data;}
export async function createProductOrderWithProof(input:{productId:string;quantity:number;whatsapp:string;paymentMethod:string;proofUrl:string;proofPublicId?:string;proofWidth?:number;proofHeight?:number;proofVersion?:string;proofResourceType?:string;}){if(!Number.isInteger(input.quantity)||input.quantity<1)throw new Error('Jumlah produk tidak valid.');const{data,error}=await supabase.rpc('create_product_order_with_proof',{p_product_id:input.productId,p_quantity:input.quantity,p_whatsapp:input.whatsapp.trim(),p_payment_method:input.paymentMethod,p_proof_url:input.proofUrl,p_proof_public_id:input.proofPublicId??null,p_proof_width:input.proofWidth??null,p_proof_height:input.proofHeight??null,p_proof_version:input.proofVersion??null,p_proof_resource_type:input.proofResourceType??null});if(error)throw error;return Array.isArray(data)?data[0]:data;}
export async function adminReviewManualOrder(orderId:string,decision:'APPROVE'|'REJECT',reason=''){const{data,error}=await supabase.rpc('admin_review_manual_order',{p_order_id:orderId,p_decision:decision,p_reason:reason.trim()||null});if(error)throw error;return Array.isArray(data)?data[0]:data;}
