import { supabase } from '@/lib/supabase';
import { liveAwards, liveCertificates, liveCompetitions, liveDailyTasks, liveFeed, liveLeaderboard, liveNotifications, liveOrders, liveUsers, liveQuestions, printCatalog, type PrintCatalogItem } from '@/data/live';
import { getPublicCompetitions, getPublicLeaderboard } from '@/services/platform.service';
import type { Award, AppNotification, Certificate, Competition, DailyTask, FeedPost, LeaderboardEntry, User, Order, OrderItem, OrderStatus } from '@/types';
import { versionedCloudinaryUrl } from '@/services/cloudinary.service';

const HYDRATE_TTL_MS = 45_000;
let lastHydrationKey = '';
let lastHydrationAt = 0;
let hydrationInFlight: { key: string; promise: Promise<void> } | null = null;

export function resetRuntimeCollections(){liveUsers.length=0;liveCompetitions.length=0;liveDailyTasks.length=0;liveLeaderboard.length=0;liveAwards.length=0;liveCertificates.length=0;liveNotifications.length=0;liveOrders.length=0;liveFeed.length=0;for(const key of Object.keys(liveQuestions))delete liveQuestions[key];printCatalog.length=0;}
function mapCompetitionStatus(status:string):Competition['status']{if(status==='REGISTRATION_OPEN')return'open';if(status==='LIVE')return'in-progress';if(status==='RESULT_PUBLISHED'||status==='ARCHIVED')return'completed';return'upcoming';}
function mapAccountRole(accountType:string|null|undefined):User['role']{if(accountType==='teacher')return'guru';if(accountType==='organizer')return'penyelenggara';return'pelajar';}
function mapEducationLevel(value:unknown):User['educationLevel']{const grade=String(value??'').toLowerCase();if(grade.startsWith('sd'))return'sd';if(grade.startsWith('smp'))return'smp';if(grade)return'sma';return undefined;}
export function mapProfileToUser(profile:any,email=''):User{const subjects=String(profile.subjects??'').split(',').map((x)=>x.trim()).filter(Boolean);return{id:profile.id,username:profile.username??'',email,displayName:profile.full_name??profile.username??'Pengguna',role:mapAccountRole(profile.account_type),bio:profile.bio??undefined,school:profile.institution??undefined,educationLevel:mapEducationLevel(profile.grade),birthDate:profile.birth_date??undefined,points:0,rank:0,joinedAt:profile.created_at,favoriteCategories:subjects as User['favoriteCategories'],profilePhoto:versionedCloudinaryUrl(profile.avatar_url,profile.avatar_version),coverPhoto:versionedCloudinaryUrl(profile.cover_url,profile.cover_version),badges:[],emblems:[],followers:0,following:0,verified:profile.status==='ACTIVE',pembina:profile.pembina||undefined,grade:profile.grade||undefined,badgeShowcase:Array.isArray(profile.badge_showcase)?profile.badge_showcase:[],badgeShowcaseManual:profile.badge_showcase_manual===true,} as any;}
export async function loadUsers(){const rows=await getPublicLeaderboard(100);liveLeaderboard.push(...rows.map((row,index):LeaderboardEntry=>({rank:Number(row.rank??index+1),userId:String(row.user_id),username:String(row.username??''),displayName:String(row.display_name??row.username??'Pengguna'),profilePhoto:row.avatar_url?String(row.avatar_url):undefined,points:Number(row.xp??0),school:row.institution?String(row.institution):undefined,educationLevel:mapEducationLevel(row.grade),emblems:[],change:row.rank_change==='up'?1:row.rank_change==='down'?-1:0,pointChange:Number(row.point_change??0),rankStatus:row.rank_change})));liveUsers.push(...liveLeaderboard.map((u):User=>({id:u.userId,username:u.username,email:'',displayName:u.displayName,role:'pelajar',school:u.school,educationLevel:u.educationLevel,points:u.points,rank:u.rank,joinedAt:'',favoriteCategories:[],profilePhoto:u.profilePhoto,badges:[],emblems:[],followers:0,following:0})));}
export async function loadCompetitions(){const rows=await getPublicCompetitions(100);const ids=rows.map(r=>String(r.id));const [levelRes,ruleRes,rewardRes,twibbonRes,questionRes]=await Promise.all([ids.length?supabase.from('competition_levels').select('competition_id,code,label,allowed_grades,points,config').in('competition_id',ids):Promise.resolve({data:[] as any[],error:null}),ids.length?supabase.from('registration_rules').select('competition_id,allowed_grades,require_twibbon,require_social_proof').in('competition_id',ids):Promise.resolve({data:[] as any[],error:null}),ids.length?supabase.from('competition_rewards').select('competition_id,rank_code,title,points,emblem_name,certificate_enabled').in('competition_id',ids).order('created_at',{ascending:true}):Promise.resolve({data:[] as any[],error:null}),ids.length?supabase.from('twibbon_templates').select('competition_id,image_url,is_active').in('competition_id',ids).eq('is_active',true):Promise.resolve({data:[] as any[],error:null}),Promise.resolve({data:[] as any[],error:null})]);for(const r of [levelRes,ruleRes,rewardRes,twibbonRes,questionRes])if(r.error)console.warn('[SykaBelajar] loadCompetitions sub-query failed:',r.error.message);const levelMap=new Map((levelRes.data??[]).map((x:any)=>[String(x.competition_id),x]));const rewardsBy=new Map<string,any[]>();for(const x of rewardRes.data??[]){const k=String(x.competition_id);if(!rewardsBy.has(k))rewardsBy.set(k,[]);rewardsBy.get(k)!.push(x);}const twibbonMap=new Map((twibbonRes.data??[]).map((x:any)=>[String(x.competition_id),x]));const questionMap=new Set<string>((questionRes.data??[]).map((x:any)=>String(x.competition_id)));liveCompetitions.push(...rows.map((row):Competition=>{const id=String(row.id),level=levelMap.get(id),tw=twibbonMap.get(id),rewards=rewardsBy.get(id)??[];return{id,slug:String(row.slug??''),title:String(row.title??''),category:String(row.category??'mtk')as Competition['category'],posterUrl:row.poster_url?String(row.poster_url):undefined,shortDesc:String(row.short_description??''),description:String(row.description??''),juknis:row.juknis_url?String(row.juknis_url):'',juknisPdfUrl:row.juknis_url?String(row.juknis_url):undefined,prizes:rewards.map((r:any)=>({position:String(r.rank_code??''),detail:String(r.title??''),emblems:r.emblem_name?[String(r.emblem_name)]:[],points:Number(r.points??0)})),points:rewards.reduce((s:number,r:any)=>s+Number(r.points??0),0),startDate:String(row.starts_at??row.registration_starts_at??''),endDate:String(row.ends_at??row.announcement_at??''),registrationDeadline:String(row.registration_ends_at??''),status:mapCompetitionStatus(String(row.status??'PUBLISHED')),participants:Number(row.participant_count??0),level:String(level?.label??level?.code??'Nasional'),twibbonUrl:tw?.image_url?String(tw.image_url):'',hasQuestions:questionMap.has(id),featured:['REGISTRATION_OPEN','LIVE'].includes(String(row.status))};}));}
export async function loadNotifications(userId:string){const{data,error}=await supabase.from('notifications').select('id,type,title,body,data,read_at,created_at').eq('user_id',userId).order('created_at',{ascending:false}).limit(50);if(error)throw error;liveNotifications.push(...((data??[])as Array<Record<string,any>>).map((n):AppNotification=>({id:String(n.id),type:n.type as AppNotification['type'],title:String(n.title??''),body:String(n.body??''),createdAt:String(n.created_at),read:Boolean(n.read_at),link:n.data?.link})));}
export async function loadAwards(userId:string){const{data,error}=await supabase.from('awards').select('id,title,rank_code,issued_at,created_at,competition_id,emblem_url,points').eq('user_id',userId).order('issued_at',{ascending:false}).limit(50);if(error)throw error;const competitionIds=[...new Set((data??[]).map((a:any)=>String(a.competition_id)).filter(Boolean))];const certQuery=competitionIds.length?supabase.from('certificates').select('id,user_id,competition_id,status').eq('user_id',userId).in('competition_id',competitionIds):Promise.resolve({data:[] as any[],error:null});const{data:certs,error:certError}=await certQuery;if(certError)throw certError;const certMap=new Map((certs??[]).map((c:any)=>[String(c.competition_id),c]));liveAwards.push(...((data??[])as Array<Record<string,any>>).map((a):Award=>{const cert=certMap.get(String(a.competition_id));return{id:String(a.id),type:cert?'certificate':'medal',title:String(a.title??''),subtitle:String(a.rank_code??''),date:String(a.issued_at??a.created_at),competitionId:a.competition_id??undefined,certificateId:cert?.id,imageUrl:a.emblem_url??undefined,color:'from-moss-400 to-moss-600',points:Number(a.points??0)};}));}
export async function loadCertificates(userId:string){const{data,error}=await supabase.from('certificates').select('id,user_id,competition_id,status,current_revision,created_at,updated_at').eq('user_id',userId).order('created_at',{ascending:false}).limit(50);if(error)throw error;const ids=(data??[]).map((c:any)=>String(c.id));let verifications:any[]=[];if(ids.length){const{data:v,error:ve}=await supabase.from('certificate_verifications').select('certificate_id,verification_code,status,public_name,competition_title,achievement_title,issued_at,revoked_at').in('certificate_id',ids);if(ve)throw ve;verifications=v??[];}const verificationMap=new Map(verifications.map((v:any)=>[String(v.certificate_id),v]));liveCertificates.push(...((data??[])as Array<Record<string,any>>).map((c):Certificate=>{const v=verificationMap.get(String(c.id));return{id:String(c.id),code:String(v?.verification_code??c.id),userId:String(c.user_id),competitionId:String(c.competition_id),competitionTitle:String(v?.competition_title??''),type:'participant',issuedAt:String(v?.issued_at??c.created_at),verified:['PUBLISHED','VERIFIED'].includes(String(v?.status??c.status))};}));}
function normalizeOrderStatus(status:unknown):OrderStatus{const value=String(status??'').toUpperCase();if(value==='PAID')return'paid';if(value==='SHIPPED')return'shipped';if(value==='COMPLETED')return'completed';if(value==='CANCELLED'||value==='CANCELED')return'cancelled';return'pending';}
function normalizeOrderCategory(productType:unknown):OrderItem['category']{const value=String(productType??'').toLowerCase();if(value.includes('medal')||value.includes('medali'))return'medali';if(value.includes('emblem'))return'emblem';return'sertifikat';}
export async function loadOrders(userId:string){const{data,error}=await supabase.from('orders').select('id,user_id,total,status,address_id,created_at,updated_at,order_items(id,product_type,name,quantity,unit_price)').eq('user_id',userId).order('created_at',{ascending:false}).limit(50);if(error)throw error;liveOrders.push(...((data??[])as Array<Record<string,any>>).map((o):Order=>({id:String(o.id),code:String(o.id),payCode:'',userId:String(o.user_id),items:(o.order_items??[]).map((i:any):OrderItem=>({id:String(i.id),category:normalizeOrderCategory(i.product_type),itemName:String(i.name??''),quantity:Number(i.quantity??1),price:Number(i.unit_price??0)})),total:Number(o.total??0),status:normalizeOrderStatus(o.status),address:String(o.address_id??''),createdAt:String(o.created_at),updatedAt:String(o.updated_at)})));}
export async function loadFeed(){const{data,error}=await supabase.from('posts').select('id,author_user_id,title,body,cover_url,created_at,competition_id').eq('status','PUBLISHED').order('created_at',{ascending:false}).limit(50);if(error){console.warn('[SykaBelajar] loadFeed failed (non-fatal):',error.message);return;}liveFeed.push(...((data??[])as Array<Record<string,any>>).map((p):FeedPost=>({id:String(p.id),userId:String(p.author_user_id),competitionId:p.competition_id??undefined,competitionSlug:p.competition_slug??undefined,title:String(p.title??''),body:String(p.body??''),createdAt:String(p.created_at),likes:0,reposts:0,image:p.cover_url??undefined,type:p.competition_id?'competition':'post',meta:p.competition_id?'Lomba':'Post',comments:[]})));}
export async function loadDailyTasks(userId?:string){if(!userId)return;const{data,error}=await supabase.from('daily_tasks').select('id,title,task_type,description,points,starts_at,created_at,ends_at,max_claims_per_user,sort_order').eq('is_active',true).order('sort_order',{ascending:true}).limit(50);if(error)throw error;liveDailyTasks.push(...((data??[])as Array<Record<string,any>>).map((t):DailyTask=>({id:String(t.id),title:String(t.title??''),type:String(t.task_type??'assignment')as DailyTask['type'],description:String(t.description??''),points:Number(t.points??0),date:String(t.starts_at??t.created_at),expiresAt:String(t.ends_at??t.created_at),completed:false,retryUsed:0,maxRetry:Number(t.max_claims_per_user??1)})));}
export async function loadPrintCatalog(){const{data,error}=await supabase.from('commerce_products').select('id,product_type,name,price,image_url,is_active,sort_order').eq('is_active',true).order('sort_order',{ascending:true}).limit(50);if(error)throw error;const allowed=new Set(['sertifikat','medali','emblem']);printCatalog.push(...((data??[])as Array<Record<string,any>>).filter((row)=>allowed.has(String(row.product_type))).map((row):PrintCatalogItem=>({id:String(row.id),category:normalizeOrderCategory(row.product_type),name:String(row.name??''),price:Number(row.price??0),preview:row.image_url?String(row.image_url):undefined})));}
export async function hydrateRuntime(userId?:string){if(!userId){resetRuntimeCollections();lastHydrationKey='';lastHydrationAt=0;hydrationInFlight=null;return;}const key=userId;const now=Date.now();if(lastHydrationKey===key&&now-lastHydrationAt<HYDRATE_TTL_MS)return;if(hydrationInFlight?.key===key){await hydrationInFlight.promise;return;}resetRuntimeCollections();const promise=Promise.allSettled([loadUsers(),loadCompetitions(),loadFeed(),loadPrintCatalog(),loadNotifications(userId),loadAwards(userId),loadCertificates(userId),loadOrders(userId),loadDailyTasks(userId)]).then(()=>{lastHydrationKey=key;lastHydrationAt=Date.now();});hydrationInFlight={key,promise};try{await promise;}finally{if(hydrationInFlight?.promise===promise)hydrationInFlight=null;}}
