import { createContext, useCallback, useContext, useEffect, useMemo, useRef, useState, type ReactNode } from 'react';
import type { Role, User, AppNotification, Order, Award, Certificate, FeedPost } from '@/types';
import { supabase } from '@/lib/supabase';
import { signIn, signUp, signOut } from '@/services/auth.service';
import { getProfileById, updateProfile as updateProfileRecord } from '@/services/profile.service';
import { hydrateRuntime, mapProfileToUser, resetRuntimeCollections } from '@/services/runtime.service';
import { liveAwards, liveCertificates, liveFeed, liveNotifications, liveOrders, liveLeaderboard } from '@/data/live';
import { backendRoleToUiRole, getUserRoles, hasAllowedLoginRole, uiRoleToAccountType } from '@/services/role.service';
import { getUnreadNotificationCount } from '@/services/notification.service';

interface AppState { user: User | null; isAuthenticated: boolean; authLoading: boolean; isGuest: boolean; notifications: AppNotification[]; unreadNotificationCount: number; refreshUnreadCount: () => Promise<void>; awards: Award[]; certificates: Certificate[]; orders: Order[]; feed: FeedPost[]; login:(email:string,password:string,requestedRole?:Exclude<Role,'admin'>)=>Promise<{ok:boolean;error?:string}>; register:(data:Partial<User>&{email:string;password:string})=>Promise<{ok:boolean;error?:string}>; loginAsGuest:()=>void; logout:()=>Promise<void>; updateProfile:(data:Partial<User>)=>Promise<void>; markNotificationRead:(id:string)=>Promise<void>; markAllNotificationsRead:()=>Promise<void>; addPoints:(points:number)=>Promise<void>; addNotification:(n:Omit<AppNotification,'id'|'createdAt'|'read'>)=>Promise<void>; addOrder:(order:Order)=>void; togglePostLike:(postId:string)=>Promise<void>; toggleCommentLike:(postId:string,commentId:string,replyId?:string)=>Promise<void>; addComment:(postId:string,body:string,parentId?:string)=>Promise<void>; toast:(message:string,type?:'success'|'error'|'info')=>void; refreshUser:()=>Promise<void>; }
const AppContext=createContext<AppState|null>(null); const GUEST_KEY='sykabelajar_guest_mode_v1';
function publishRuntimeState(setters:{setNotifications:(v:AppNotification[])=>void;setAwards:(v:Award[])=>void;setCertificates:(v:Certificate[])=>void;setOrders:(v:Order[])=>void;setFeed:(v:FeedPost[])=>void}){setters.setNotifications([...liveNotifications]);setters.setAwards([...liveAwards]);setters.setCertificates([...liveCertificates]);setters.setOrders([...liveOrders]);setters.setFeed([...liveFeed]);}
function preferredRole(roles:Awaited<ReturnType<typeof getUserRoles>>):Role{if(roles.includes('admin'))return'admin';if(roles.includes('organizer_member'))return'penyelenggara';if(roles.includes('teacher'))return'guru';return'pelajar';}
export function AppProvider({children}:{children:ReactNode}){const[authUser,setAuthUser]=useState<{id:string;email?:string}|null>(null);const[user,setUser]=useState<User|null>(null);const[userReady,setUserReady]=useState(false);const[authLoading,setAuthLoading]=useState(true);const[isGuest,setIsGuest]=useState(()=>localStorage.getItem(GUEST_KEY)==='1');const isGuestRef=useRef(isGuest);isGuestRef.current=isGuest;const[notifications,setNotifications]=useState<AppNotification[]>([]);const[unreadNotificationCount,setUnreadNotificationCount]=useState(0);const[awards,setAwards]=useState<Award[]>([]);const[certificates,setCertificates]=useState<Certificate[]>([]);const[orders,setOrders]=useState<Order[]>([]);const[feed,setFeed]=useState<FeedPost[]>([]);const[toasts,setToasts]=useState<{id:string;message:string;type:'success'|'error'|'info'}[]>([]);const publish=useCallback(()=>publishRuntimeState({setNotifications,setAwards,setCertificates,setOrders,setFeed}),[]);
 // ── Refresh unread notification count from DB ──
 const refreshUnreadCount=useCallback(async(userIdOverride?:string)=>{const uid=userIdOverride||authUser?.id;if(!uid||isGuest){setUnreadNotificationCount(0);return;}try{const c=await getUnreadNotificationCount(uid);setUnreadNotificationCount(c);}catch{}},[authUser,isGuest]);
 // ── Auth intent tracking ──
 const loggedOutRef=useRef(false);
 const suppressNextSignOutRef=useRef(false);
 const authUserRef=useRef(authUser);
 authUserRef.current=authUser;
 // ── Alive ref (shared between auth useEffect and visibility handler) ──
 const aliveRef=useRef(true);
 const refreshRuntime=useCallback(async(userId?:string,email?:string)=>{if(userId)setUserReady(false);try{await hydrateRuntime(userId);publish();if(userId){const profile=await getProfileById(userId);if(!profile)throw new Error('PROFILE_NOT_FOUND');const mapped=mapProfileToUser(profile,email);const leaderboardEntry=liveLeaderboard.find((entry)=>entry.userId===userId);let role=mapped.role;try{role=preferredRole(await getUserRoles(userId));}catch(roleError){console.warn('[SykaBelajar] role lookup failed',roleError);}setUser({...mapped,role,points:leaderboardEntry?.points??mapped.points,rank:leaderboardEntry?.rank??mapped.rank});setUserReady(true);}else{setUser(null);setUserReady(false);}}catch(error){console.error('[SykaBelajar] runtime hydration failed',error);publish();if(userId)setUser(null);setUserReady(false);}},[publish]);
 // ── Tab focus: proactive token refresh (MOVED OUTSIDE useEffect to fix Rules of Hooks) ──
 const handleVisibility=useCallback(()=>{if(document.visibilityState!=='visible'||!authUserRef.current||isGuestRef.current||!aliveRef.current)return;suppressNextSignOutRef.current=true;void supabase.auth.getSession().then(({data:{session}})=>{if(!session?.user&&aliveRef.current&&authUserRef.current){suppressNextSignOutRef.current=false;void(async()=>{try{const r2=await supabase.auth.getSession();const s=r2.data.session as any;if(!s?.user&&aliveRef.current){setAuthUser(null);setUser(null);setUserReady(false);if(!isGuestRef.current){resetRuntimeCollections();publish();await refreshRuntime();}}}catch{}})();}});},[publish,refreshRuntime]);
 useEffect(()=>{document.addEventListener('visibilitychange',handleVisibility);return()=>document.removeEventListener('visibilitychange',handleVisibility);},[handleVisibility]);
 useEffect(()=>{aliveRef.current=true;let mounted=false;const bootstrap=async()=>{try{const{data,error}=await supabase.auth.getSession();if(!aliveRef.current||error)return;if(data.session?.user){const sessionUser={id:data.session.user.id,email:data.session.user.email??undefined};setAuthUser(sessionUser);setIsGuest(false);localStorage.removeItem(GUEST_KEY);await refreshRuntime(sessionUser.id,sessionUser.email);void refreshUnreadCount(sessionUser.id);}else{resetRuntimeCollections();publish();setAuthUser(null);setUser(null);setUserReady(false);await refreshRuntime();}}catch(error){console.error('[SykaBelajar] auth bootstrap failed',error);if(aliveRef.current){setAuthUser(null);setUser(null);setUserReady(false);}}finally{if(aliveRef.current){setAuthLoading(false);mounted=true;}}};void bootstrap();
 // ── Auth state change listener ──
 const{data:subscription}=supabase.auth.onAuthStateChange((_event,session: any)=>{if(!aliveRef.current)return;
 if(session?.user){const sessionUser={id:session.user.id,email:session.user.email??undefined};setAuthUser(sessionUser);setIsGuest(false);localStorage.removeItem(GUEST_KEY);suppressNextSignOutRef.current=false;return;}
 if(!session){if(_event==='SIGNED_OUT'){if(!mounted){suppressNextSignOutRef.current=true;return;}
 if(loggedOutRef.current){loggedOutRef.current=false;suppressNextSignOutRef.current=false;return;}
 if(suppressNextSignOutRef.current){suppressNextSignOutRef.current=false;return;}
 void(async()=>{try{const result=await supabase.auth.getSession();const recovered=result.data.session as any;if(recovered?.user&&aliveRef.current){setAuthUser({id:recovered.user.id,email:recovered.user.email??undefined});suppressNextSignOutRef.current=true;return;}}catch{}if(aliveRef.current){setAuthUser(null);setUser(null);setUserReady(false);if(!isGuestRef.current){resetRuntimeCollections();publish();window.setTimeout(()=>{if(aliveRef.current)void refreshRuntime();},0);}}})();return;}else if(_event==='INITIAL_SESSION'){if(!session?.user&&aliveRef.current){setAuthUser(null);setUser(null);setUserReady(false);void refreshRuntime();}}}});
 return()=>{aliveRef.current=false;subscription.subscription.unsubscribe();};},[publish,refreshRuntime]);
 const toast=useCallback((message:string,type:'success'|'error'|'info'='success')=>{const id=crypto.randomUUID();setToasts(items=>[...items,{id,message,type}]);window.setTimeout(()=>setToasts(items=>items.filter(x=>x.id!==id)),3500);},[]);
 const login=useCallback(async(email:string,password:string,requestedRole:Exclude<Role,'admin'>='pelajar')=>{try{const result=await signIn(email.trim(),password);if(!result.user)return{ok:false,error:'Login gagal: sesi pengguna tidak tersedia.'};const roles=await getUserRoles(result.user.id);if(!roles.length){await signOut();return{ok:false,error:'Akun belum memiliki role aktif di backend.'};}if(!hasAllowedLoginRole(roles,requestedRole)){await signOut();const roleNames=roles.map(role=>backendRoleToUiRole(role)).join(', ');return{ok:false,error:`Role akun adalah ${roleNames}. Pilih jenis akun yang sesuai.`};}setAuthUser({id:result.user.id,email:result.user.email??undefined});setIsGuest(false);localStorage.removeItem(GUEST_KEY);await refreshRuntime(result.user.id,result.user.email??undefined);return{ok:true};}catch(error:any){return{ok:false,error:error?.message??'Email atau password tidak valid.'};}},[refreshRuntime]);
 const register=useCallback(async(data:Partial<User>&{email:string;password:string})=>{try{const requestedRole=data.role==='guru'||data.role==='penyelenggara'?data.role:'pelajar';await signUp(data.email.trim(),data.password,{username:data.username??'',full_name:data.displayName??'',account_type:uiRoleToAccountType(requestedRole),birth_date:data.birthDate,institution:data.school,grade:data.educationLevel,subjects:Array.isArray(data.favoriteCategories)?data.favoriteCategories.join(','):undefined});return{ok:true};}catch(error:any){return{ok:false,error:error?.message??'Pendaftaran gagal.'};}},[]);
 const loginAsGuest=useCallback(()=>{localStorage.setItem(GUEST_KEY,'1');setIsGuest(true);setAuthUser(null);setUser(null);setUserReady(false);resetRuntimeCollections();publish();void refreshRuntime();},[publish,refreshRuntime]);const logout=useCallback(async()=>{loggedOutRef.current=true;try{await signOut();}finally{localStorage.removeItem(GUEST_KEY);setAuthUser(null);setUser(null);setUserReady(false);setIsGuest(false);resetRuntimeCollections();publish();void refreshRuntime();}},[publish,refreshRuntime]);const refreshUser=useCallback(async()=>{if(!authUser)return;try{const profile=await getProfileById(authUser.id);if(!profile)return;const mapped=mapProfileToUser(profile,authUser.email);let role=mapped.role;try{role=preferredRole(await getUserRoles(authUser.id));}catch{}setUser(current=>current?{...current,...mapped,role}:{...mapped,role});}catch(e){console.warn('[SykaBelajar] refreshUser failed',e);}},[authUser]);
 const updateProfile=useCallback(async(data:Partial<User>)=>{if(!authUser)return;const patch:Record<string,unknown>={};if(data.displayName!==undefined)patch.full_name=data.displayName;if(data.bio!==undefined)patch.bio=data.bio;if(data.school!==undefined)patch.institution=data.school;if(data.birthDate!==undefined)patch.birth_date=data.birthDate;if(data.profilePhoto!==undefined)patch.avatar_url=data.profilePhoto;if(data.educationLevel!==undefined)patch.grade=data.educationLevel;if(data.favoriteCategories!==undefined)patch.subjects=Array.isArray(data.favoriteCategories)?data.favoriteCategories.join(','):data.favoriteCategories;const fresh=await updateProfileRecord(authUser.id,patch);const mapped=mapProfileToUser(fresh,authUser.email);let role=mapped.role;try{role=preferredRole(await getUserRoles(authUser.id));}catch{}setUser(current=>current?{...current,...mapped,role}:{...mapped,role});},[authUser]);
 const markNotificationRead=useCallback(async(id:string)=>{if(!authUser)return;setNotifications(items=>items.map(n=>n.id===id?{...n,read:true}:n));setUnreadNotificationCount(c=>Math.max(0,c-1));try{await supabase.from('notifications').update({read_at:new Date().toISOString()}).eq('id',id).eq('user_id',authUser.id);}catch(e){console.warn('[SykaBelajar] markNotificationRead DB sync failed',e);}},[authUser]);const markAllNotificationsRead=useCallback(async()=>{if(!authUser)return;setNotifications(items=>items.map(n=>({...n,read:true})));setUnreadNotificationCount(0);try{await supabase.from('notifications').update({read_at:new Date().toISOString()}).eq('user_id',authUser.id).is('read_at',null);}catch(e){console.warn('[SykaBelajar] markAllNotificationsRead DB sync failed',e);}},[authUser]);const addPoints=useCallback(async(_points:number)=>{throw new Error('XP hanya boleh diberikan oleh backend/server-authoritative workflows.');},[]);
 const addNotification=useCallback(async(n:Omit<AppNotification,'id'|'createdAt'|'read'>)=>{if(!authUser)return;const{data,error}=await supabase.from('notifications').insert({user_id:authUser.id,type:n.type,title:n.title,body:n.body,data:{link:n.link,icon:n.icon}}).select('*').single();if(error)throw error;setNotifications(items=>[{id:data.id,type:data.type,title:data.title,body:data.body??'',createdAt:data.created_at,read:false,link:data.data?.link},...items]);},[authUser]);const addOrder=useCallback((order:Order)=>setOrders(items=>[order,...items]),[]);
 const togglePostLike=useCallback(async(postId:string)=>{if(!authUser)return;const{data:existing,error:lookupError}=await supabase.from('post_likes').select('post_id').eq('post_id',postId).eq('user_id',authUser.id).maybeSingle();if(lookupError)throw lookupError;if(existing){const{error}=await supabase.from('post_likes').delete().eq('post_id',postId).eq('user_id',authUser.id);if(error)throw error;}else{const{error}=await supabase.from('post_likes').insert({post_id:postId,user_id:authUser.id});if(error)throw error;}void refreshRuntime(authUser.id,authUser.email);},[authUser,refreshRuntime]);const toggleCommentLike=useCallback(async(_postId:string,commentId:string)=>{if(!authUser)return;const{data:existing,error:lookupError}=await supabase.from('comment_likes').select('comment_id').eq('comment_id',commentId).eq('user_id',authUser.id).maybeSingle();if(lookupError)throw lookupError;if(existing){const{error}=await supabase.from('comment_likes').delete().eq('comment_id',commentId).eq('user_id',authUser.id);if(error)throw error;}else{const{error}=await supabase.from('comment_likes').insert({comment_id:commentId,user_id:authUser.id});if(error)throw error;}void refreshRuntime(authUser.id,authUser.email);},[authUser,refreshRuntime]);const addComment=useCallback(async(postId:string,body:string,parentId?:string)=>{if(!authUser||!body.trim())return;const{error}=await supabase.from('comments').insert({post_id:postId,user_id:authUser.id,parent_id:parentId??null,body:body.trim(),moderation_state:'PUBLISHED'});if(error)throw error;void refreshRuntime(authUser.id,authUser.email);},[authUser,refreshRuntime]);
 const value=useMemo<AppState>(()=>({user,isAuthenticated:!!authUser,authLoading,isGuest,notifications,unreadNotificationCount,refreshUnreadCount,awards,certificates,orders,feed,login,register,loginAsGuest,logout,updateProfile,markNotificationRead,markAllNotificationsRead,addPoints,addNotification,addOrder,togglePostLike,toggleCommentLike,addComment,toast,refreshUser}),[user,authUser,userReady,isGuest,notifications,unreadNotificationCount,refreshUnreadCount,awards,certificates,orders,feed,login,register,loginAsGuest,logout,updateProfile,markNotificationRead,markAllNotificationsRead,addPoints,addNotification,addOrder,togglePostLike,toggleCommentLike,addComment,toast]);
 return <AppContext.Provider value={value}>{children}<div className="fixed bottom-20 md:bottom-6 left-1/2 -translate-x-1/2 z-[100] flex flex-col gap-2 items-center pointer-events-none">{toasts.map(t=><div key={t.id} className={`pointer-events-auto px-4 py-3 rounded-xl shadow-pop text-sm font-medium animate-slide-up flex items-center gap-2 ${t.type==='success'?'bg-moss-600 text-white':t.type==='error'?'bg-err text-white':'surface-elevated text-white'}`}><span className="w-1.5 h-1.5 rounded-full bg-white/80"/>{t.message}</div>)}</div></AppContext.Provider>;
}
export function useApp(){const ctx=useContext(AppContext);if(!ctx)throw new Error('useApp must be used within AppProvider');return ctx;}
