import { useEffect, useState } from 'react';
import { ArrowLeft, ArrowRight, KeyRound, ShieldCheck } from 'lucide-react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { verifyCollectiveParticipantAccess } from '@/services/collectiveParticipant.service';
import { toast } from '@/lib/toast';

export function CollectiveParticipantLoginPage(){
  const navigate=useNavigate(); const[searchParams]=useSearchParams(); const[stage,setStage]=useState<1|2>(1); const[code,setCode]=useState(''); const[password,setPassword]=useState(''); const[busy,setBusy]=useState(false);
  useEffect(()=>{const initial=searchParams.get('code')?.trim().toUpperCase();if(initial)setCode(initial)},[searchParams]);
  const next=()=>{if(!code.trim())return toast.error('Kode peserta wajib diisi untuk memilih akses lomba.');setStage(2)};
  const submit=async()=>{if(!code.trim())return toast.error('Kode peserta wajib diisi.');if(!password)return toast.error('Password akses wajib diisi.');setBusy(true);try{const result=await verifyCollectiveParticipantAccess(code,password);if(result?.ok!==true){const reason=String(result?.reason||'INVALID_CREDENTIALS');toast.error(reason==='LOCKED'?'Akses terkunci sementara. Coba lagi nanti.':reason==='ACCESS_NOT_READY'?'Akses peserta belum siap.':'Kode peserta atau password salah.');return}sessionStorage.setItem('syka_collective_access_token',String(result.access_token||''));sessionStorage.setItem('syka_collective_participant',JSON.stringify(result));navigate('/peserta-kolektif',{replace:true})}catch(e:any){toast.error(e?.message||'Gagal masuk.')}finally{setBusy(false)}};
  return <div className="min-h-screen surface-bg flex items-center justify-center p-5"><Card className="w-full max-w-md p-6"><Link to="/" className="inline-flex items-center gap-2 text-xs text-fg-muted hover:text-fg"><ArrowLeft size={14}/> Beranda</Link><div className="mt-6 text-center"><div className="mx-auto w-12 h-12 rounded-2xl bg-accent/10 flex items-center justify-center text-accent"><ShieldCheck size={24}/></div><h1 className="text-2xl font-bold text-fg mt-4">Portal Peserta</h1><p className="text-sm text-fg-muted mt-1">Akses bertahap menjaga sesi tetap terikat pada peserta dan lombanya.</p></div><div className="mt-6"><div className="flex items-center gap-2 mb-5"><div className={`h-2 flex-1 rounded-full ${stage>=1?'bg-moss-500':'surface-elevated'}`}/><div className={`h-2 flex-1 rounded-full ${stage>=2?'bg-moss-500':'surface-elevated'}`}/></div>{stage===1?<div className="space-y-4"><div><p className="text-xs text-fg-muted">Tahap 1 · Pilih akses lomba</p><label className="block mt-2"><span className="text-xs text-fg-muted">Kode peserta</span><input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} autoCapitalize="characters" placeholder="CP-XXXXXXXXXX" className="mt-1 w-full rounded-xl border border-border bg-transparent px-3 py-3 text-sm font-mono"/></label><p className="text-[11px] text-fg-muted mt-2">Kode peserta menentukan event yang boleh dibuka dan bukan password.</p></div><Button className="w-full" onClick={next} icon={<ArrowRight size={15}/>}>Lanjut ke password</Button></div>:<div className="space-y-4"><div><p className="text-xs text-fg-muted">Tahap 2 · Autentikasi portal</p><div className="mt-2 rounded-xl border border-border p-3"><p className="text-[10px] text-fg-muted uppercase tracking-wider">Peserta</p><p className="font-mono text-sm text-fg mt-1">{code}</p></div></div><label className="block"><span className="text-xs text-fg-muted">Password akses pribadi</span><input autoFocus type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password" className="mt-1 w-full rounded-xl border border-border bg-transparent px-3 py-3 text-sm" onKeyDown={e=>{if(e.key==='Enter')void submit()}}/></label><div className="flex gap-2"><Button variant="outline" onClick={()=>setStage(1)}>Kembali</Button><Button className="flex-1" onClick={()=>void submit()} loading={busy} icon={<KeyRound size={15}/>}>Masuk ke portal</Button></div></div>}</div><p className="text-[11px] text-fg-muted mt-5 text-center">Password disimpan sebagai hash di backend; sesi memiliki masa berlaku terbatas dan dapat dicabut.</p></Card></div>;
}
