import { useEffect, useState } from 'react';
import { ArrowLeft, BadgeCheck, Download, ShieldCheck } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { supabase } from '@/lib/supabase';

export function CollectiveCertificatePage(){
 const{code=''}=useParams();const[certificate,setCertificate]=useState<Record<string,unknown>|null>(null);const[loading,setLoading]=useState(true);const[downloading,setDownloading]=useState(false);
 useEffect(()=>{let active=true;(async()=>{try{const{data,error}=await supabase.rpc('get_public_collective_certificate',{p_verification_code:code});if(error)throw error;if(active)setCertificate(data as Record<string,unknown>);}catch{if(active)setCertificate(null)}finally{if(active)setLoading(false)}})();return()=>{active=false}},[code]);
 if(loading)return <div className="min-h-screen surface-bg flex items-center justify-center text-fg-muted">Memuat sertifikat…</div>;
 if(!certificate)return <div className="min-h-screen surface-bg p-5"><div className="max-w-xl mx-auto"><Card className="p-8 text-center"><ShieldCheck className="mx-auto text-fg-muted" size={32}/><h1 className="text-xl font-bold text-fg mt-3">Sertifikat tidak ditemukan</h1><p className="text-sm text-fg-muted mt-2">Kode verifikasi tidak valid atau belum tersedia.</p><Link className="inline-block mt-5 text-sm text-accent hover:underline" to="/">Kembali ke SYKABELAJAR</Link></Card></div></div>;
 const revoked=String(certificate.status)==='REVOKED';
 const downloadPdf=async()=>{try{setDownloading(true);const res=await fetch(`${import.meta.env.VITE_SUPABASE_URL}/functions/v1/generate-collective-certificate-pdf?code=${encodeURIComponent(code)}`,{redirect:'follow'});if(!res.ok)throw new Error('PDF tidak tersedia.');const blob=await res.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`sertifikat-${code}.pdf`;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}catch(err){window.alert(err instanceof Error?err.message:'PDF tidak tersedia.')}finally{setDownloading(false)}};
 return <div className="min-h-screen surface-bg p-5 md:p-10"><div className="max-w-5xl mx-auto space-y-4 print:max-w-none print:p-0"><div className="flex items-center justify-between print:hidden"><Link to={`/verify/${String(certificate.verification_code||code)}`} className="inline-flex items-center gap-2 text-xs text-fg-muted hover:text-fg"><ArrowLeft size={14}/> Verifikasi</Link>{revoked?<span className="text-xs font-semibold text-rose-600">SERTIFIKAT DICABUT</span>:<Button size="sm" onClick={downloadPdf} disabled={downloading} icon={<Download size={14}/>}>{downloading?'Membuat PDF…':'Download PDF'}</Button>}</div><div className={`bg-white text-slate-900 min-h-[680px] rounded-3xl border p-10 md:p-16 shadow-xl print:shadow-none print:rounded-none print:min-h-screen ${revoked?'opacity-80':''}`}><div className="h-full border-4 border-slate-800 rounded-2xl p-8 md:p-14 flex flex-col items-center justify-center text-center"><BadgeCheck size={54} className="text-slate-800"/><p className="text-sm font-semibold tracking-[0.22em] mt-5">SYKABELAJAR</p><h1 className="text-4xl font-bold mt-3">SERTIFIKAT</h1><p className="text-lg mt-8">Diberikan kepada</p><p className="text-3xl font-bold mt-3">{String(certificate.public_name||'Peserta')}</p><p className="text-base mt-4">atas partisipasi pada</p><p className="text-xl font-semibold mt-2">{String(certificate.competition_title||'Kompetisi')}</p>{certificate.achievement_title?<p className="text-lg font-semibold mt-3">{String(certificate.achievement_title)}</p>:null}<div className="grid sm:grid-cols-2 gap-5 mt-10 w-full max-w-2xl text-left"><div className="rounded-xl border p-4"><p className="text-xs text-slate-500">Nomor serial</p><p className="font-mono font-semibold mt-1">{String(certificate.serial_number||'Menunggu penerbitan')}</p></div><div className="rounded-xl border p-4"><p className="text-xs text-slate-500">Kode verifikasi</p><p className="font-mono font-semibold mt-1">{String(certificate.verification_code||code)}</p></div></div>{revoked?<div className="mt-8 rounded-xl border-2 border-rose-300 bg-rose-50 p-4 text-rose-700"><p className="font-bold">REVOKED</p><p className="text-sm mt-1">Sertifikat ini telah dicabut. QR dan kode verifikasinya tetap dapat diperiksa untuk menampilkan status ini.</p></div>:<p className="text-sm text-slate-500 mt-8">Diterbitkan {certificate.issued_at?new Date(String(certificate.issued_at)).toLocaleDateString('id-ID'): '—'}.</p>}</div></div></div></div>;
}
