import { useEffect, useState } from 'react';
import { ArrowLeft, KeyRound, ShieldCheck } from 'lucide-react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { verifyCollectivePortalPassword } from '@/services/collectiveParticipant.service';
import { toast } from '@/lib/toast';

export function CollectiveParticipantLoginPage(){
 const navigate=useNavigate(); const[searchParams]=useSearchParams(); const[password,setPassword]=useState(''); const[busy,setBusy]=useState(false); const[pendingCode,setPendingCode]=useState('');
 useEffect(()=>{setPendingCode(String(searchParams.get('code')||'').trim().toUpperCase())},[searchParams]);
 const submit=async()=>{if(!password)return toast.error('Password portal wajib diisi.');setBusy(true);try{const result=await verifyCollectivePortalPassword(password);if(result?.ok!==true){const reason=String(result?.reason||'INVALID_CREDENTIALS');toast.error(reason==='LOCKED'?'Akses terkunci sementara. Coba lagi nanti.':reason==='ACCESS_NOT_READY'?'Portal peserta belum siap.':'Password portal salah.');return}sessionStorage.setItem('syka_collective_portal_token',String(result.portal_token||''));if(pendingCode)sessionStorage.setItem('syka_collective_pending_code',pendingCode);else sessionStorage.removeItem('syka_collective_pending_code');sessionStorage.removeItem('syka_collective_access_token');sessionStorage.removeItem('syka_collective_participant');navigate('/peserta-kolektif',{replace:true})}catch(e:unknown){toast.error(e instanceof Error?e.message:'Gagal masuk ke portal.')}finally{setBusy(false)}};
 return <div className="min-h-screen surface-bg flex items-center justify-center p-5"><Card className="w-full max-w-md p-6"><Link to="/" className="inline-flex items-center gap-2 text-xs text-fg-muted hover:text-fg"><ArrowLeft size={14}/> Beranda</Link><div className="mt-6 text-center"><div className="mx-auto w-12 h-12 rounded-2xl bg-accent/10 flex items-center justify-center text-accent"><ShieldCheck size={24}/></div><h1 className="text-2xl font-bold text-fg mt-4">Portal Peserta</h1><p className="text-sm text-fg-muted mt-1">Masuk ke portal terlebih dahulu. Lomba dan kode peserta dipilih pada tahap berikutnya.</p></div><div className="mt-6 space-y-4"><label className="block"><span className="text-xs text-fg-muted">Password portal pribadi</span><input autoFocus type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password" className="mt-1 w-full rounded-xl border border-border bg-transparent px-3 py-3 text-sm" onKeyDown={e=>{if(e.key==='Enter')void submit()}}/></label><Button className="w-full" onClick={()=>void submit()} loading={busy} icon={<KeyRound size={15}/>}>Masuk ke portal</Button></div>{pendingCode?<p className="text-[11px] text-fg-muted mt-4 text-center">QR terdeteksi. Kode <span className="font-mono text-fg">{pendingCode}</span> akan diprioritaskan setelah portal terbuka.</p>:null}<p className="text-[11px] text-fg-muted mt-5 text-center">Password portal di-hash di backend, memiliki lockout brute-force, dan menghasilkan sesi portal terbatas.</p></Card></div>;
}