import { useEffect, useState } from 'react';
import { ArrowLeft, Award, ExternalLink, Trophy } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Card } from '@/components/ui/Card';
import { Badge } from '@/components/ui/Badge';
import { supabase } from '@/lib/supabase';
import { toast } from '@/lib/toast';

type Row={participant_id:string;competition_id:string;competition_title:string;participant_code:string;full_name:string;attempt_status:string|null;score:number|null;rank:number|null;result_published:boolean;certificate_status:string|null;serial_number:string|null;verification_code:string|null;certificate_url:string|null;issued_at:string|null};
export function CollectiveHistoryPage(){const[rows,setRows]=useState<Row[]>([]);const[loading,setLoading]=useState(true);useEffect(()=>{(async()=>{try{const{data,error}=await supabase.rpc('list_my_claimed_collective_history');if(error)throw error;setRows((data??[])as Row[])}catch(e){toast.error(e instanceof Error?e.message:'Gagal memuat riwayat kolektif.')}finally{setLoading(false)}})()},[]);return <div className="min-h-screen surface-bg text-fg-secondary p-5 md:p-8"><div className="max-w-4xl mx-auto space-y-5"><Link to="/home" className="inline-flex items-center gap-2 text-xs text-fg-muted hover:text-fg"><ArrowLeft size={14}/> Kembali</Link><div><p className="text-xs text-accent font-semibold tracking-wider">RIWAYAT KOLEKTIF</p><h1 className="text-2xl md:text-3xl font-bold text-fg">Lomba yang sudah ditautkan</h1><p className="text-sm text-fg-muted mt-1">Riwayat peserta kolektif yang sudah di-claim ke akun penuh kamu.</p></div>{loading?<Card className="p-8 text-center text-fg-muted">Memuat riwayat…</Card>:rows.length===0?<Card className="p-8 text-center text-fg-muted">Belum ada riwayat kolektif yang ditautkan.</Card>:rows.map(row=><Card key={row.participant_id} className="p-5"><div className="flex flex-col md:flex-row md:items-start gap-4"><div className="w-12 h-12 rounded-2xl bg-accent/10 flex items-center justify-center text-accent"><Trophy size={21}/></div><div className="flex-1"><p className="text-xs text-accent font-semibold">{row.competition_title}</p><h2 className="text-lg font-semibold text-fg mt-1">{row.full_name}</h2><p className="text-xs text-fg-muted mt-1 font-mono">{row.participant_code}</p>{row.result_published?<div className="flex flex-wrap gap-2 mt-3"><Badge color="moss"><Trophy size={12}/> Peringkat #{row.rank??0}</Badge><Badge color="moss">Skor {Number(row.score??0)}</Badge></div>:<p className="text-sm text-fg-muted mt-3">Hasil belum dipublikasikan.</p>}</div><div className="md:text-right"><div className="flex items-center gap-2 md:justify-end"><Award size={16} className="text-accent"/><span className="text-sm text-fg">Sertifikat</span></div>{row.certificate_status==='PUBLISHED'&&row.verification_code?<><p className="text-xs text-fg-muted mt-1">{row.serial_number}</p><Link className="inline-flex items-center gap-1 text-xs text-accent mt-2 hover:underline" to={`/sertifikat-kolektif/${row.verification_code}`}>Lihat sertifikat <ExternalLink size={11}/></Link></>:<p className="text-xs text-fg-muted mt-1">Belum diterbitkan</p>}</div></div></Card>)}</div></div>}
