import { useEffect, useMemo, useState } from 'react';
import { Link, useSearchParams, useParams } from 'react-router-dom';
import { ArrowLeft, Lock, Search, UserCheck, UserMinus } from 'lucide-react';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Avatar } from '@/components/ui/Avatar';
import { useApp } from '@/store/AppContext';
import { supabase } from '@/lib/supabase';
import { blockChatUser, removeFollow } from '@/services/chat.service';

export function FollowersPage(){
 const{username}=useParams();const{user,toast}=useApp();const[params,setParams]=useSearchParams();const mode=params.get('tab')==='following'?'following':'followers';const[rows,setRows]=useState<any[]>([]);const[loading,setLoading]=useState(true);const[search,setSearch]=useState('');
 useEffect(()=>{let live=true;(async()=>{setLoading(true);try{const{data:p}=await supabase.from('profiles').select('id,username').eq('username',username||'').maybeSingle();if(!p){setRows([]);return;}const{data:f,error}=await supabase.from('follows').select('follower_id,following_id,status').eq(mode==='followers'?'following_id':'follower_id',p.id).in('status',['approved','auto']);if(error)throw error;const ids=(f??[]).map(x=>mode==='followers'?x.follower_id:x.following_id);if(!ids.length){setRows([]);return;}const{data:profiles,error:pe}=await supabase.from('profiles').select('id,username,full_name,avatar_url,verification_type').in('id',ids);if(pe)throw pe;if(live)setRows((profiles??[]).sort((a,b)=>String(a.username).localeCompare(String(b.username))));}catch(e:any){if(live)toast(e?.message??'Gagal memuat daftar pengguna.','error');}finally{if(live)setLoading(false);}})();return()=>{live=false;};},[username,mode,toast]);
 const filtered=useMemo(()=>rows.filter(r=>`${r.full_name??''} ${r.username??''}`.toLowerCase().includes(search.toLowerCase())),[rows,search]);
 const setMode=(next:'followers'|'following')=>{setParams(prev=>{prev.set('tab',next);return prev;});};
 const block=async(id:string)=>{try{await blockChatUser(id);setRows(p=>p.filter(x=>x.id!==id));toast('Pengguna diblokir.','success');}catch(e:any){toast(e?.message??'Gagal memblokir pengguna.','error');}};
 const unfollow=async(id:string)=>{try{await removeFollow(id);setRows(p=>p.filter(x=>x.id!==id));toast('Berhenti mengikuti.','info');}catch(e:any){toast(e?.message??'Gagal berhenti mengikuti.','error');}};
 return <div className="min-h-screen p-4 md:p-6"><div className="mx-auto max-w-2xl"><Link to={`/profile/${username}`} className="mb-4 inline-flex items-center gap-2 text-xs text-fg-muted hover:text-fg"><ArrowLeft size={14}/>Kembali ke profil</Link><Card className="overflow-hidden"><div className="border-b surface-border p-4"><h1 className="text-lg font-bold text-fg">{mode==='followers'?'Pengikut':'Mengikuti'}</h1><div className="mt-3 flex gap-1 rounded-xl surface-elevated p-1"><button onClick={()=>setMode('followers')} className={`flex-1 rounded-lg px-3 py-2 text-xs font-semibold ${mode==='followers'?'bg-accent-muted-strong text-accent':'text-fg-muted'}`}>Pengikut</button><button onClick={()=>setMode('following')} className={`flex-1 rounded-lg px-3 py-2 text-xs font-semibold ${mode==='following'?'bg-accent-muted-strong text-accent':'text-fg-muted'}`}>Mengikuti</button></div><div className="relative mt-3"><Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-fg-muted"/><input className="input pl-9" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cari username..."/></div></div><div className="divide-y surface-border">{loading?<div className="p-8 text-center text-sm text-fg-muted">Memuat…</div>:filtered.length===0?<div className="p-8 text-center text-sm text-fg-muted">Tidak ada pengguna.</div>:filtered.map(p=><div key={p.id} className="flex items-center gap-3 p-4"><Link to={`/profile/${p.username}`} className="flex min-w-0 flex-1 items-center gap-3"><Avatar name={p.full_name||p.username} id={p.id} size={42} src={p.avatar_url||undefined}/><div className="min-w-0"><p className="truncate text-sm font-semibold text-fg">{p.full_name||p.username}</p><p className="truncate text-xs text-fg-muted">@{p.username}</p></div></Link>{user&&user.id!==p.id&&<><button title="Blokir chat" onClick={()=>void block(p.id)} className="rounded-lg p-2 text-red-400 hover:bg-red-500/10"><Lock size={15}/></button>{mode==='following'&&<button title="Unfollow" onClick={()=>void unfollow(p.id)} className="rounded-lg p-2 text-fg-muted hover:bg-white/5"><UserMinus size={15}/></button>}</>}</div>)}</div></Card></div></div>;
}
