import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ExternalLink, ImagePlus, RefreshCw, Upload, Download, ZoomIn, ZoomOut } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import { supabase } from '@/lib/supabase';
import { uploadImage, deleteImage } from '@/services/cloudinary.service';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { useApp } from '@/store/AppContext';
import { getCompetitionBySlug } from '@/services/competition.service';
import { submitRegistration } from '@/services/registration.service';

export function TwibbonPage(){
 const{slug=''}=useParams();const navigate=useNavigate();const{user,toast}=useApp();
 const[file,setFile]=useState<File|null>(null);const[preview,setPreview]=useState('');const[templates,setTemplates]=useState<any[]>([]);const[registration,setRegistration]=useState<any>(null);const[postUrl,setPostUrl]=useState('');const[platform,setPlatform]=useState<'instagram'|'tiktok'>('instagram');const[socialUsername,setSocialUsername]=useState('');const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[competition,setCompetition]=useState<any>(null);
 const[mode,setMode]=useState<'external'|'canvas'>('external');const[scale,setScale]=useState(1);const[x,setX]=useState(0);const[y,setY]=useState(0);const canvasRef=useRef<HTMLCanvasElement|null>(null);const photoRef=useRef<HTMLImageElement|null>(null);const frameRef=useRef<HTMLImageElement|null>(null);
 useEffect(()=>{if(!file){setPreview('');return;}const u=URL.createObjectURL(file);setPreview(u);return()=>URL.revokeObjectURL(u)},[file]);
 const load=async()=>{if(!user?.id)return;setLoading(true);try{const c=await getCompetitionBySlug(slug);if(!c){toast('Lomba tidak ditemukan.','error');return;}setCompetition(c);setMode(c.twibbon_mode==='canvas'?'canvas':'external');const[{data:t},{data:r}]=await Promise.all([supabase.from('twibbon_templates').select('*').eq('competition_id',c.id).eq('is_active',true).order('created_at',{ascending:false}),supabase.from('registrations').select('*').eq('competition_id',c.id).eq('user_id',user.id).order('created_at',{ascending:false}).limit(1).maybeSingle()]);setTemplates(t??[]);setRegistration(r);setPostUrl(r?.social_proof_url??'');setPlatform(r?.metadata?.social_platform==='tiktok'?'tiktok':'instagram');setSocialUsername(r?.metadata?.social_username??'');}catch(e:any){toast(e?.message??'Gagal memuat Twibbon.','error')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[slug,user?.id]);
 useEffect(()=>{if(mode!=='canvas'||!preview)return;let disposed=false;const p=new Image();p.onload=()=>{if(disposed) return;photoRef.current=p;draw();};p.src=preview;return()=>{disposed=true}},[preview,mode,scale,x,y]);
 useEffect(()=>{if(mode!=='canvas'||!competition?.twibbon_frame_url)return;let disposed=false;const f=new Image();f.crossOrigin='anonymous';f.onload=()=>{if(disposed)return;frameRef.current=f;draw()};f.src=competition.twibbon_frame_url;return()=>{disposed=true}},[competition?.twibbon_frame_url,mode,scale,x,y]);
 const draw=()=>{const canvas=canvasRef.current;if(!canvas||!photoRef.current)return;const frame=frameRef.current;const size=900;canvas.width=size;canvas.height=size;const ctx=canvas.getContext('2d');if(!ctx)return;ctx.clearRect(0,0,size,size);ctx.fillStyle='#fff';ctx.fillRect(0,0,size,size);const img=photoRef.current;const cover=Math.max(size/img.width,size/img.height)*scale;const w=img.width*cover,h=img.height*cover;ctx.drawImage(img,(size-w)/2+x,(size-h)/2+y,w,h);if(frame)ctx.drawImage(frame,0,0,size,size)};
 const flatten=()=>{const canvas=canvasRef.current;if(!canvas)throw new Error('Canvas belum siap.');return new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('Gagal membuat hasil Twibbon.')),'image/png',0.95))};
 const download=async()=>{try{const blob=await flatten();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`twibbon-${slug}.png`;a.click();URL.revokeObjectURL(url)}catch(e:any){toast(e.message,'error')}};
 const submit=async()=>{if(!user)return;setSaving(true);try{const c=competition??await getCompetitionBySlug(slug);if(!c)throw new Error('Lomba tidak ditemukan.');let reg=registration;if(!reg){const created=await submitRegistration({competitionId:c.id,userId:user.id,socialPlatform:platform,socialUsername,socialProofUrl:postUrl});reg=created.record;setRegistration(reg)}let oldPublicId=reg?.twibbon_public_id as string|undefined;
   if(mode==='canvas'){
     if(!c.twibbon_frame_url)throw new Error('Frame Twibbon belum dikonfigurasi.');
     const blob=await flatten();const generated=new File([blob],`twibbon-${c.id}.png`,{type:'image/png'});const up=await uploadImage(generated,`sykabelajar/twibbon/${c.id}/${user.id}`);const{error}=await supabase.from('registrations').update({twibbon_asset_url:up.secure_url,twibbon_public_id:up.public_id,metadata:{...(reg?.metadata??{}),social_platform:platform,social_username:socialUsername.trim().replace(/^@+/,'')},updated_at:new Date().toISOString()}).eq('id',reg.id).eq('user_id',user.id);if(error)throw error;if(oldPublicId&&oldPublicId!==up.public_id)void deleteImage(oldPublicId);setRegistration({...reg,twibbon_asset_url:up.secure_url,twibbon_public_id:up.public_id});toast('Twibbon hasil canvas berhasil disimpan.','success');
   }else{
     const{error}=await supabase.from('registrations').update({social_proof_url:postUrl.trim(),metadata:{...(reg.metadata??{}),social_platform:platform,social_username:socialUsername.trim().replace(/^@+/,'')},submitted_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',reg.id).eq('user_id',user.id);if(error)throw error;toast('Bukti pendaftaran tersimpan.','success');
   }
   await load();
 }catch(e:any){toast(e?.message??'Gagal menyimpan Twibbon.','error')}finally{setSaving(false)}};
 if(!user)return <div className="p-8 text-center text-slate-400">Silakan login terlebih dahulu.</div>;
 return <div className="min-h-screen p-4 md:p-6"><div className="max-w-5xl mx-auto space-y-4"><div className="flex items-center gap-3"><button onClick={()=>navigate(-1)} className="p-2 rounded-lg hover:bg-white/5"><ArrowLeft size={19}/></button><div className="flex-1"><p className="text-xs text-accent uppercase">Twibbon</p><h1 className="font-display text-2xl font-bold text-fg">{mode==='canvas'?'Editor Twibbon':'Kirim bukti pendaftaran'}</h1></div><Button variant="outline" onClick={()=>void load()} loading={loading} icon={<RefreshCw size={14}/>}>Refresh</Button></div>
 {mode==='canvas'?<>
 <Card className="p-5"><h2 className="font-semibold text-fg">Editor Twibbon Premium</h2><p className="text-xs text-fg-muted mt-1">Unggah foto, atur posisi dan ukuran, lalu download atau simpan hasilnya.</p><div className="grid lg:grid-cols-[1fr_280px] gap-5 mt-4"><div className="space-y-3"><div className="aspect-square max-w-[560px] mx-auto rounded-2xl overflow-hidden surface-elevated border surface-border flex items-center justify-center"><canvas ref={canvasRef} className="w-full h-full"/>{!preview&&<div className="absolute text-center text-fg-muted"><ImagePlus size={40} className="mx-auto mb-2"/><p className="text-sm">Pilih foto untuk mulai.</p></div>}</div><div className="flex justify-center gap-2"><label className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-moss-600 text-white text-sm cursor-pointer"><Upload size={16}/><span>{file?'Ganti Foto':'Pilih Foto'}</span><input type="file" accept="image/*" className="hidden" disabled={saving} onChange={e=>setFile(e.target.files?.[0]??null)}/></label><Button variant="outline" onClick={()=>void download()} disabled={!preview} icon={<Download size={16}/>}>Download PNG</Button></div></div><div className="space-y-4"><div><p className="text-xs font-semibold text-fg mb-2">Perbesar / Perkecil</p><div className="flex items-center gap-2"><Button size="sm" variant="outline" onClick={()=>setScale(v=>Math.max(.5,v-.1))} icon={<ZoomOut size={14}/>}/><input type="range" min="0.5" max="2" step="0.05" value={scale} onChange={e=>setScale(Number(e.target.value))} className="flex-1"/><Button size="sm" variant="outline" onClick={()=>setScale(v=>Math.min(2,v+.1))} icon={<ZoomIn size={14}/>}/></div></div><div><p className="text-xs font-semibold text-fg mb-2">Posisi Horizontal</p><input type="range" min="-250" max="250" step="1" value={x} onChange={e=>setX(Number(e.target.value))} className="w-full"/></div><div><p className="text-xs font-semibold text-fg mb-2">Posisi Vertikal</p><input type="range" min="-250" max="250" step="1" value={y} onChange={e=>setY(Number(e.target.value))} className="w-full"/></div><div className="rounded-xl border surface-border p-3 text-xs text-fg-muted">Frame berasal dari Cloudinary dan selalu berada di lapisan paling atas. Hasil final dapat dipakai sebagai bukti Twibbon.</div>{registration?.twibbon_asset_url&&<img src={registration.twibbon_asset_url} alt="Twibbon tersimpan" className="w-full rounded-xl border surface-border"/>}</div></div></Card>
 </>:<><Card className="p-5"><h2 className="font-semibold text-fg">1. Template aktif</h2><div className="grid sm:grid-cols-2 gap-3 mt-4">{templates.map(t=><a href={t.image_url} target="_blank" rel="noreferrer" key={t.id} className="rounded-xl border surface-border overflow-hidden"><img src={t.image_url} alt={t.name} className="aspect-video w-full object-cover"/><div className="p-3 flex items-center justify-between"><span className="text-sm text-fg">{t.name}</span><ExternalLink size={14}/></div></a>)}{!templates.length&&<p className="text-sm text-slate-500">Belum ada template aktif.</p>}</div></Card><Card className="p-5"><h2 className="font-semibold text-fg">2. Bukti sosial</h2><p className="text-xs text-fg-muted mt-1">Paket Free menggunakan tautan external Twibbon. Masukkan tautan hasil posting yang bisa diperiksa penyelenggara.</p></Card></>}
 <Card className="p-5"><h2 className="font-semibold text-fg">{mode==='canvas'?'Informasi Pendaftaran':'2. Social proof'}</h2><div className="grid sm:grid-cols-2 gap-3 mt-4"><select className="input" value={platform} onChange={e=>setPlatform(e.target.value as any)}><option value="instagram">Instagram</option><option value="tiktok">TikTok</option></select><input className="input" value={socialUsername} onChange={e=>setSocialUsername(e.target.value)} placeholder="Username sosial"/><input className="input sm:col-span-2" value={postUrl} onChange={e=>setPostUrl(e.target.value)} placeholder="https://instagram.com/..."/></div><Button className="mt-4" loading={saving} onClick={()=>void submit()}>{mode==='canvas'?'Simpan Twibbon & Pendaftaran':'Kirim Pendaftaran & Bukti'}</Button></Card>
 </div></div>;
}
