ALTER TABLE public.competitions ADD COLUMN IF NOT EXISTS twibbon_external_url text;

DROP FUNCTION IF EXISTS public.create_organizer_competition(uuid,text,text,text,text,text,text,text,text,timestamptz,timestamptz,timestamptz,timestamptz,timestamptz,text[],text[],text[],text[],text,text,text);
CREATE OR REPLACE FUNCTION public.create_organizer_competition(p_organizer_id uuid,p_title text,p_slug text,p_category text,p_short_description text,p_description text,p_poster_url text,p_poster_public_id text,p_visibility text,p_registration_starts_at timestamptz,p_registration_ends_at timestamptz,p_starts_at timestamptz,p_ends_at timestamptz,p_announcement_at timestamptz,p_category_codes text[],p_excluded_category_codes text[],p_target_grades text[],p_excluded_grades text[],p_twibbon_mode text,p_twibbon_external_url text,p_twibbon_frame_url text,p_twibbon_frame_public_id text) RETURNS public.competitions LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public','private' AS $$ DECLARE u uuid:=auth.uid();plan text;v public.competitions;BEGIN IF u IS NULL THEN RAISE EXCEPTION 'AUTH_REQUIRED';END IF;IF NOT private.current_user_is_admin() AND NOT private.current_user_is_organizer_for(p_organizer_id) THEN RAISE EXCEPTION 'FORBIDDEN';END IF;IF p_twibbon_mode='canvas' THEN SELECT op.plan_code INTO plan FROM public.organizer_plans op WHERE op.organizer_id=p_organizer_id AND op.is_active=true AND op.starts_at<=now() AND(op.ends_at IS NULL OR op.ends_at>now()) ORDER BY op.starts_at DESC LIMIT 1;IF NOT EXISTS(SELECT 1 FROM public.plan_entitlements pe WHERE pe.plan_code=plan AND pe.capability='twibbon_canvas' AND coalesce(pe.limit_value,0)>0) THEN RAISE EXCEPTION 'PREMIUM_REQUIRED';END IF;END IF;INSERT INTO public.competitions(organizer_id,title,slug,category,short_description,description,poster_url,poster_public_id,visibility,status,registration_starts_at,registration_ends_at,starts_at,ends_at,announcement_at,category_codes,excluded_category_codes,target_grades,excluded_grades,twibbon_mode,twibbon_external_url,twibbon_frame_url,twibbon_frame_public_id)VALUES(p_organizer_id,p_title,p_slug,p_category,p_short_description,p_description,p_poster_url,p_poster_public_id,coalesce(p_visibility,'PUBLIC'),'DRAFT',p_registration_starts_at,p_registration_ends_at,p_starts_at,p_ends_at,p_announcement_at,p_category_codes,p_excluded_category_codes,p_target_grades,p_excluded_grades,coalesce(p_twibbon_mode,'external'),p_twibbon_external_url,p_twibbon_frame_url,p_twibbon_frame_public_id)RETURNING * INTO v;RETURN v;END;$$;

ALTER TABLE public.daily_checkin_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_checkin_overrides ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_checkin_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_checkins ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS daily_checkin_settings_admin_all ON public.daily_checkin_settings;
DROP POLICY IF EXISTS daily_checkin_overrides_admin_all ON public.daily_checkin_overrides;
DROP POLICY IF EXISTS daily_checkin_events_admin_all ON public.daily_checkin_events;
DROP POLICY IF EXISTS daily_checkins_select_own ON public.daily_checkins;
CREATE POLICY daily_checkin_settings_admin_all ON public.daily_checkin_settings FOR ALL TO authenticated USING (private.current_user_is_admin()) WITH CHECK (private.current_user_is_admin());
CREATE POLICY daily_checkin_overrides_admin_all ON public.daily_checkin_overrides FOR ALL TO authenticated USING (private.current_user_is_admin()) WITH CHECK (private.current_user_is_admin());
CREATE POLICY daily_checkin_events_admin_all ON public.daily_checkin_events FOR ALL TO authenticated USING (private.current_user_is_admin()) WITH CHECK (private.current_user_is_admin());
CREATE POLICY daily_checkins_select_own ON public.daily_checkins FOR SELECT TO authenticated USING (user_id=auth.uid());
