create table if not exists public.platform_settings (id uuid primary key default gen_random_uuid(), key text not null unique, value jsonb not null default '{}'::jsonb, updated_at timestamptz not null default now());
create table if not exists public.ad_banner_settings (id uuid primary key default gen_random_uuid(), slide_duration_seconds int not null default 45, min_duration_seconds int not null default 30, max_duration_seconds int not null default 60, price_per_lot_daily numeric(12,2) not null default 50000, bundle_discount_3lots numeric(5,2) not null default 15, bundle_discount_5lots numeric(5,2) not null default 25, single_image_2slots_price numeric(12,2) not null default 80000, single_image_3slots_price numeric(12,2) not null default 100000, created_at timestamptz not null default now());
create table if not exists public.ad_banner_requests (id uuid primary key default gen_random_uuid(), organizer_id uuid references public.organizers(id) on delete cascade, user_id uuid references auth.users(id) on delete cascade, image_url text not null default '', image_urls text[] not null default '{}', media_type text not null default 'image', link_url text not null default '/home', slots_requested int not null default 1, single_image boolean not null default false, duration_days int not null default 7, total_price numeric(12,2) not null default 0, status text not null default 'PENDING', admin_note text, reviewed_at timestamptz, created_at timestamptz not null default now());
create table if not exists public.ad_banners (id uuid primary key default gen_random_uuid(), title text not null default '', image_url text not null default '', link_url text, is_active boolean default true, sort_order integer default 0, created_at timestamptz not null default now());
alter table public.ad_banners add column if not exists request_id uuid references public.ad_banner_requests(id) on delete set null;
alter table public.ad_banners add column if not exists organizer_id uuid references public.organizers(id) on delete set null;
alter table public.ad_banners add column if not exists user_id uuid references auth.users(id) on delete set null;
alter table public.ad_banners add column if not exists slot_number int;
alter table public.ad_banners add column if not exists image_urls text[] not null default '{}';
alter table public.ad_banners add column if not exists media_type text not null default 'image';
alter table public.ad_banners add column if not exists single_image boolean not null default false;
alter table public.ad_banners add column if not exists image_width_slots int not null default 1;
alter table public.ad_banners add column if not exists slide_duration_seconds int not null default 45;
alter table public.ad_banners add column if not exists expires_at timestamptz;
update public.ad_banners set slot_number=coalesce(slot_number,sort_order+1), image_urls=case when cardinality(image_urls)=0 then array[image_url] else image_urls end, expires_at=coalesce(expires_at,now()+interval '365 days') where slot_number is null or cardinality(image_urls)=0 or expires_at is null;
create unique index if not exists ad_banners_slot_number_key on public.ad_banners(slot_number);
alter table public.platform_settings enable row level security;
alter table public.ad_banner_settings enable row level security;
alter table public.ad_banner_requests enable row level security;
alter table public.ad_banners enable row level security;
drop policy if exists platform_settings_public_read on public.platform_settings;
create policy platform_settings_public_read on public.platform_settings for select to anon,authenticated using (true);
drop policy if exists platform_settings_admin_write on public.platform_settings;
create policy platform_settings_admin_write on public.platform_settings for all to authenticated using (public.is_active_admin(auth.uid())) with check (public.is_active_admin(auth.uid()));
drop policy if exists ad_banner_settings_public_read on public.ad_banner_settings;
create policy ad_banner_settings_public_read on public.ad_banner_settings for select to anon,authenticated using (true);
drop policy if exists ad_banner_settings_admin_write on public.ad_banner_settings;
create policy ad_banner_settings_admin_write on public.ad_banner_settings for all to authenticated using (public.is_active_admin(auth.uid())) with check (public.is_active_admin(auth.uid()));
drop policy if exists ad_banner_requests_owner_read on public.ad_banner_requests;
create policy ad_banner_requests_owner_read on public.ad_banner_requests for select to authenticated using (user_id=auth.uid() or public.is_active_admin(auth.uid()));
drop policy if exists ad_banner_requests_owner_insert on public.ad_banner_requests;
create policy ad_banner_requests_owner_insert on public.ad_banner_requests for insert to authenticated with check (user_id=auth.uid());
drop policy if exists ad_banner_requests_admin_write on public.ad_banner_requests;
create policy ad_banner_requests_admin_write on public.ad_banner_requests for all to authenticated using (public.is_active_admin(auth.uid())) with check (public.is_active_admin(auth.uid()));
drop policy if exists ad_banners_public_read on public.ad_banners;
create policy ad_banners_public_read on public.ad_banners for select to anon,authenticated using (is_active=true and (expires_at is null or expires_at>now()));
drop policy if exists ad_banners_admin_write on public.ad_banners;
create policy ad_banners_admin_write on public.ad_banners for all to authenticated using (public.is_active_admin(auth.uid())) with check (public.is_active_admin(auth.uid()));
grant select on public.platform_settings, public.ad_banner_settings, public.ad_banners to anon,authenticated;
grant select,insert,update,delete on public.platform_settings, public.ad_banner_settings, public.ad_banner_requests, public.ad_banners to authenticated;
create or replace view public.public_profiles with (security_invoker=true) as select id,username,full_name,institution,avatar_url from public.profiles;
grant select on public.public_profiles to anon,authenticated;
