create table if not exists private.collective_chat_realtime_sessions(auth_user_id uuid primary key references auth.users(id) on delete cascade,collective_participant_id uuid not null references public.collective_participants(id) on delete cascade,competition_id uuid not null references public.competitions(id) on delete cascade,expires_at timestamptz not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists idx_collective_chat_realtime_competition on private.collective_chat_realtime_sessions(competition_id,expires_at);
alter table private.collective_chat_realtime_sessions enable row level security;
revoke all on table private.collective_chat_realtime_sessions from anon,authenticated;

create or replace function private.collective_realtime_bind(p_access_token text) returns jsonb language plpgsql security definer set search_path=public,private,extensions as $$
declare v_uid uuid:=auth.uid();v_cp uuid:=private.collective_session_participant(trim(coalesce(p_access_token,'')));v_competition uuid;v_expires timestamptz;
begin
 if v_uid is null then raise exception 'AUTH_REQUIRED';end if;if v_cp is null then raise exception 'COLLECTIVE_SESSION_INVALID';end if;
 select competition_id into v_competition from public.collective_participants where id=v_cp and status='ACTIVE';if v_competition is null then raise exception 'COLLECTIVE_SESSION_INVALID';end if;
 select least(s.expires_at,now()+interval '8 hours') into v_expires from public.collective_access_sessions s where s.token_hash=private.hash_collective_token(trim(coalesce(p_access_token,''))) and s.revoked_at is null and s.expires_at>now() and s.session_type='COMPETITION' and s.collective_participant_id=v_cp order by s.created_at desc limit 1;if v_expires is null then raise exception 'COLLECTIVE_SESSION_INVALID';end if;
 insert into private.collective_chat_realtime_sessions(auth_user_id,collective_participant_id,competition_id,expires_at,updated_at) values(v_uid,v_cp,v_competition,v_expires,now()) on conflict(auth_user_id) do update set collective_participant_id=excluded.collective_participant_id,competition_id=excluded.competition_id,expires_at=excluded.expires_at,updated_at=now();
 return jsonb_build_object('ok',true,'competition_id',v_competition,'expires_at',v_expires);
end;$$;
revoke all on function private.collective_realtime_bind(text) from public;grant execute on function private.collective_realtime_bind(text) to authenticated;

create or replace function private.collective_realtime_can_read(p_competition_id uuid) returns boolean language sql security definer stable set search_path=public,private as $$
 select auth.uid() is not null and(exists(select 1 from private.collective_chat_realtime_sessions s where s.auth_user_id=auth.uid() and s.competition_id=p_competition_id and s.expires_at>now()) or exists(select 1 from public.collective_participants cp where cp.competition_id=p_competition_id and cp.managed_by_user_id=auth.uid() and cp.status='ACTIVE') or exists(select 1 from public.organizer_members om join public.competitions c on c.organizer_id=om.organizer_id where c.id=p_competition_id and om.user_id=auth.uid() and om.is_active=true and om.status='ACTIVE') or exists(select 1 from public.user_roles ur where ur.user_id=auth.uid() and ur.role='admin' and ur.is_active=true));$$;
revoke all on function private.collective_realtime_can_read(uuid) from public;

drop policy if exists collective_chat_scoped_select on public.collective_chat_messages;
create policy collective_chat_scoped_select on public.collective_chat_messages for select to authenticated using(private.collective_realtime_can_read(competition_id));
alter table public.collective_chat_messages enable row level security;grant select on public.collective_chat_messages to authenticated;revoke insert,update,delete on public.collective_chat_messages from anon,authenticated;
create index if not exists idx_collective_chat_sender_recent on public.collective_chat_messages(collective_participant_id,created_at desc);
do $$ begin if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='collective_chat_messages') then alter publication supabase_realtime add table public.collective_chat_messages;end if;end $$;

drop function if exists public.get_collective_chat_messages(text,uuid,integer);
create function public.get_collective_chat_messages(p_access_token text,p_competition_id uuid,p_limit integer default 50) returns table(id uuid,sender_kind text,sender_role text,sender_name text,body text,created_at timestamptz) language sql security definer set search_path=public,private,extensions as $$
 select m.id,m.sender_kind,case when m.sender_kind='PARTICIPANT' then 'PARTICIPANT' when exists(select 1 from public.user_roles ur where ur.user_id=m.sender_user_id and ur.role='admin' and ur.is_active=true) then 'ADMIN' when exists(select 1 from public.collective_participants cp3 where cp3.competition_id=m.competition_id and cp3.managed_by_user_id=m.sender_user_id and cp3.status='ACTIVE') then 'TEACHER' when exists(select 1 from public.organizer_members om join public.competitions c2 on c2.organizer_id=om.organizer_id where c2.id=m.competition_id and om.user_id=m.sender_user_id and om.is_active=true and om.status='ACTIVE') then 'ORGANIZER' else coalesce(m.sender_kind,'USER') end,coalesce(case when m.sender_kind='PARTICIPANT' then cp.full_name else p.full_name end,'Pengguna'),m.body,m.created_at from public.collective_chat_messages m left join public.collective_participants cp on cp.id=m.collective_participant_id left join public.profiles p on p.id=m.sender_user_id join public.competitions c on c.id=m.competition_id where m.competition_id=p_competition_id and(exists(select 1 from public.collective_participants cp2 where cp2.id=private.collective_session_participant(p_access_token) and cp2.competition_id=p_competition_id and cp2.status='ACTIVE') or exists(select 1 from public.collective_participants cp3 where cp3.competition_id=p_competition_id and cp3.managed_by_user_id=auth.uid()) or exists(select 1 from public.organizer_members om where om.organizer_id=c.organizer_id and om.user_id=auth.uid() and om.is_active=true and om.status='ACTIVE') or exists(select 1 from public.user_roles ur where ur.user_id=auth.uid() and ur.role='admin' and ur.is_active=true)) order by m.created_at desc limit greatest(1,least(coalesce(p_limit,50),100));$$;

create or replace function public.send_collective_participant_chat_message(p_access_token text,p_body text) returns public.collective_chat_messages language plpgsql security definer set search_path=public,private,extensions as $$
declare v_cp uuid:=private.collective_session_participant(trim(coalesce(p_access_token,'')));v_row public.collective_chat_messages%rowtype;v_body text:=trim(coalesce(p_body,''));v_count integer;
begin
 if v_cp is null then raise exception 'COLLECTIVE_SESSION_INVALID';end if;if char_length(v_body)<1 or char_length(v_body)>2000 then raise exception 'CHAT_BODY_INVALID';end if;
 select count(*) into v_count from public.collective_chat_messages where collective_participant_id=v_cp and created_at>now()-interval '1 minute';if v_count>=10 then raise exception 'CHAT_RATE_LIMIT';end if;
 if exists(select 1 from public.collective_chat_messages where collective_participant_id=v_cp and body=v_body and created_at>now()-interval '10 seconds') then raise exception 'CHAT_DUPLICATE';end if;
 insert into public.collective_chat_messages(competition_id,collective_participant_id,sender_user_id,sender_kind,body) select cp.competition_id,cp.id,null,'PARTICIPANT',v_body from public.collective_participants cp where cp.id=v_cp and cp.status='ACTIVE' returning * into v_row;return v_row;
end;$$;